# Generated by Django 5.2.10 on 2026-01-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exportjob',
            new_name='reporting_e_tenant__d9144d_idx',
            old_name='reporting_e_tenant__a1b2c3_idx',
        ),
    ]
