# Generated by Django 5.2.11 on 2026-02-09 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardStatementRef',
            fields=[
                ('code', models.CharField(help_text='H-Code (z.B. H225)', max_length=10, primary_key=True, serialize=False)),
                ('text_de', models.TextField(help_text='Deutscher Text')),
                ('text_en', models.TextField(blank=True, default='', help_text='English text')),
                ('category', models.CharField(blank=True, default='', help_text='Kategorie (physikalisch, Gesundheit, Umwelt)', max_length=50)),
            ],
            options={
                'verbose_name': 'H-Satz (Referenz)',
                'verbose_name_plural': 'H-Sätze (Referenz)',
                'db_table': 'substances_ref_hazard_statement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PictogramRef',
            fields=[
                ('code', models.CharField(help_text='GHS-Code (z.B. GHS01)', max_length=10, primary_key=True, serialize=False)),
                ('name_de', models.CharField(help_text='Deutscher Name', max_length=100)),
                ('name_en', models.CharField(blank=True, default='', help_text='English name', max_length=100)),
                ('svg_path', models.CharField(blank=True, default='', help_text='Pfad zur SVG-Datei', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Beschreibung der Gefahr')),
            ],
            options={
                'verbose_name': 'Piktogramm (Referenz)',
                'verbose_name_plural': 'Piktogramme (Referenz)',
                'db_table': 'substances_ref_pictogram',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PrecautionaryStatementRef',
            fields=[
                ('code', models.CharField(help_text='P-Code (z.B. P210, P210+P233)', max_length=20, primary_key=True, serialize=False)),
                ('text_de', models.TextField(help_text='Deutscher Text')),
                ('text_en', models.TextField(blank=True, default='', help_text='English text')),
                ('category', models.CharField(blank=True, default='', help_text='Kategorie (Prävention, Reaktion, Lagerung, Entsorgung)', max_length=50)),
            ],
            options={
                'verbose_name': 'P-Satz (Referenz)',
                'verbose_name_plural': 'P-Sätze (Referenz)',
                'db_table': 'substances_ref_precautionary_statement',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(help_text='Firmenname', max_length=240)),
                ('party_type', models.CharField(choices=[('manufacturer', 'Hersteller'), ('supplier', 'Lieferant')], help_text='Typ der Partei', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Partei',
                'verbose_name_plural': 'Parteien',
                'db_table': 'substances_party',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id', 'party_type'], name='ix_party_tenant_type')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'party_type', 'name'), name='uq_party_tenant_type_name')],
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(help_text='Stoffname / Produktbezeichnung', max_length=240)),
                ('trade_name', models.CharField(blank=True, default='', help_text='Handelsname', max_length=240)),
                ('description', models.TextField(blank=True, default='', help_text='Beschreibung / Verwendungszweck')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('archived', 'Archiviert')], default='active', max_length=20)),
                ('storage_class', models.CharField(blank=True, choices=[('1', '1 - Explosive Stoffe'), ('2A', '2A - Verdichtete Gase'), ('2B', '2B - Druckgaspackungen'), ('3', '3 - Entzündbare Flüssigkeiten'), ('4.1A', '4.1A - Selbstzersetzliche Stoffe'), ('4.1B', '4.1B - Desensibilisierte explosive Stoffe'), ('4.2', '4.2 - Pyrophore/selbsterhitzungsfähige Stoffe'), ('4.3', '4.3 - Stoffe, die mit Wasser reagieren'), ('5.1A', '5.1A - Stark oxidierende Stoffe'), ('5.1B', '5.1B - Oxidierende Stoffe'), ('5.1C', '5.1C - Ammoniumnitrat'), ('5.2', '5.2 - Organische Peroxide'), ('6.1A', '6.1A - Brennbare akut toxische Stoffe'), ('6.1B', '6.1B - Nicht brennbare akut toxische Stoffe'), ('6.1C', '6.1C - Brennbare chronisch toxische Stoffe'), ('6.1D', '6.1D - Nicht brennbare chronisch toxische'), ('6.2', '6.2 - Ansteckungsgefährliche Stoffe'), ('7', '7 - Radioaktive Stoffe'), ('8A', '8A - Brennbare ätzende Stoffe'), ('8B', '8B - Nicht brennbare ätzende Stoffe'), ('10', '10 - Brennbare Flüssigkeiten (nicht LGK 3)'), ('11', '11 - Brennbare Feststoffe'), ('12', '12 - Nicht brennbare Flüssigkeiten'), ('13', '13 - Nicht brennbare Feststoffe')], default='', help_text='Lagerklasse nach TRGS 510', max_length=10)),
                ('is_cmr', models.BooleanField(default=False, help_text='CMR-Stoff (karzinogen, mutagen, reproduktionstoxisch)')),
                ('flash_point_c', models.FloatField(blank=True, help_text='Flammpunkt in °C', null=True)),
                ('ignition_temperature_c', models.FloatField(blank=True, help_text='Zündtemperatur in °C', null=True)),
                ('lower_explosion_limit', models.FloatField(blank=True, help_text='Untere Explosionsgrenze (UEG) in Vol.%', null=True)),
                ('upper_explosion_limit', models.FloatField(blank=True, help_text='Obere Explosionsgrenze (OEG) in Vol.%', null=True)),
                ('temperature_class', models.CharField(blank=True, default='', help_text='Temperaturklasse (T1-T6)', max_length=10)),
                ('explosion_group', models.CharField(blank=True, default='', help_text='Explosionsgruppe (IIA, IIB, IIC)', max_length=10)),
                ('vapor_density', models.FloatField(blank=True, help_text='Dampfdichte (Luft = 1)', null=True)),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'party_type': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_substances', to='substances.party')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'party_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_substances', to='substances.party')),
            ],
            options={
                'verbose_name': 'Gefahrstoff',
                'verbose_name_plural': 'Gefahrstoffe',
                'db_table': 'substances_substance',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Menge', max_digits=12)),
                ('unit', models.CharField(default='kg', help_text='Einheit (kg, l, m³)', max_length=20)),
                ('state', models.CharField(choices=[('solid', 'Fest'), ('liquid', 'Flüssig'), ('gas', 'Gasförmig')], default='liquid', help_text='Aggregatzustand', max_length=20)),
                ('storage_location', models.CharField(blank=True, default='', help_text='Lagerort (z.B. Gefahrstofflager A)', max_length=200)),
                ('responsible_user', models.UUIDField(blank=True, help_text='Verantwortliche Person', null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_inventory', to='tenancy.site')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='substances.substance')),
            ],
            options={
                'verbose_name': 'Standort-Inventar',
                'verbose_name_plural': 'Standort-Inventar',
                'db_table': 'substances_site_inventory',
            },
        ),
        migrations.CreateModel(
            name='SdsRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('revision_date', models.DateField(help_text='Datum des SDS')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'Zur Freigabe'), ('approved', 'Freigegeben'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('signal_word', models.CharField(choices=[('danger', 'Gefahr'), ('warning', 'Achtung'), ('none', 'Kein Signalwort')], default='none', max_length=20)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(blank=True, help_text='Verknüpftes PDF-Dokument', null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.documentversion')),
                ('hazard_statements', models.ManyToManyField(blank=True, related_name='sds_revisions', to='substances.hazardstatementref')),
                ('pictograms', models.ManyToManyField(blank=True, related_name='sds_revisions', to='substances.pictogramref')),
                ('precautionary_statements', models.ManyToManyField(blank=True, related_name='sds_revisions', to='substances.precautionarystatementref')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds_revisions', to='substances.substance')),
            ],
            options={
                'verbose_name': 'SDS-Revision',
                'verbose_name_plural': 'SDS-Revisionen',
                'db_table': 'substances_sds_revision',
                'ordering': ['-revision_date', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='LocationSubstanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('area_id', models.UUIDField(db_index=True, help_text='Standort/Bereich (Area-ID)')),
                ('substance_name', models.CharField(help_text='Denormalisierter Stoffname', max_length=300)),
                ('cas_number', models.CharField(blank=True, default='', max_length=30)),
                ('max_quantity_kg', models.DecimalField(decimal_places=2, default=0, help_text='Maximale Lagermenge in kg', max_digits=12)),
                ('current_quantity_kg', models.DecimalField(decimal_places=2, default=0, help_text='Aktuelle Lagermenge in kg', max_digits=12)),
                ('storage_class', models.CharField(blank=True, choices=[('1', '1 - Explosive Stoffe'), ('2A', '2A - Verdichtete Gase'), ('2B', '2B - Druckgaspackungen'), ('3', '3 - Entzündbare Flüssigkeiten'), ('4.1A', '4.1A - Selbstzersetzliche Stoffe'), ('4.1B', '4.1B - Desensibilisierte explosive Stoffe'), ('4.2', '4.2 - Pyrophore/selbsterhitzungsfähige Stoffe'), ('4.3', '4.3 - Stoffe, die mit Wasser reagieren'), ('5.1A', '5.1A - Stark oxidierende Stoffe'), ('5.1B', '5.1B - Oxidierende Stoffe'), ('5.1C', '5.1C - Ammoniumnitrat'), ('5.2', '5.2 - Organische Peroxide'), ('6.1A', '6.1A - Brennbare akut toxische Stoffe'), ('6.1B', '6.1B - Nicht brennbare akut toxische Stoffe'), ('6.1C', '6.1C - Brennbare chronisch toxische Stoffe'), ('6.1D', '6.1D - Nicht brennbare chronisch toxische'), ('6.2', '6.2 - Ansteckungsgefährliche Stoffe'), ('7', '7 - Radioaktive Stoffe'), ('8A', '8A - Brennbare ätzende Stoffe'), ('8B', '8B - Nicht brennbare ätzende Stoffe'), ('10', '10 - Brennbare Flüssigkeiten (nicht LGK 3)'), ('11', '11 - Brennbare Feststoffe'), ('12', '12 - Nicht brennbare Flüssigkeiten'), ('13', '13 - Nicht brennbare Feststoffe')], db_index=True, default='', max_length=10)),
                ('seveso_category', models.CharField(choices=[('none', 'Nicht Seveso-relevant'), ('lower', 'Untere Klasse (Grundpflichten)'), ('upper', 'Obere Klasse (Erweiterte Pflichten)')], db_index=True, default='none', max_length=10)),
                ('seveso_threshold_lower_t', models.DecimalField(blank=True, decimal_places=2, help_text='Untere Mengenschwelle (Tonnen)', max_digits=10, null=True)),
                ('seveso_threshold_upper_t', models.DecimalField(blank=True, decimal_places=2, help_text='Obere Mengenschwelle (Tonnen)', max_digits=10, null=True)),
                ('h_statements', models.TextField(blank=True, default='')),
                ('ghs_pictograms', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_inventory_date', models.DateField(blank=True, null=True)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_entries', to='substances.substance')),
            ],
            options={
                'db_table': 'substances_location_entry',
                'ordering': ['substance_name'],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('cas', 'CAS-Nummer'), ('ec', 'EC-Nummer'), ('ufi', 'UFI-Code'), ('gtin', 'GTIN/EAN'), ('internal', 'Interne Nummer'), ('index', 'Index-Nummer'), ('reach', 'REACH-Registrierungsnr.')], max_length=20)),
                ('id_value', models.CharField(max_length=100)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='substances.substance')),
            ],
            options={
                'verbose_name': 'Stoffkennung',
                'verbose_name_plural': 'Stoffkennungen',
                'db_table': 'substances_identifier',
            },
        ),
        migrations.AddIndex(
            model_name='substance',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_substance_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='substance',
            index=models.Index(fields=['tenant_id', 'is_cmr'], name='ix_substance_tenant_cmr'),
        ),
        migrations.AddIndex(
            model_name='substance',
            index=models.Index(fields=['name'], name='ix_substance_name'),
        ),
        migrations.AddConstraint(
            model_name='substance',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uq_substance_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='siteinventoryitem',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'site', 'substance', 'storage_location'), name='uq_inventory_site_substance_location'),
        ),
        migrations.AddConstraint(
            model_name='sdsrevision',
            constraint=models.UniqueConstraint(fields=('substance', 'revision_number'), name='uq_sds_substance_revision'),
        ),
        migrations.AddConstraint(
            model_name='locationsubstanceentry',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'area_id', 'substance_id'), name='uq_location_substance'),
        ),
        migrations.AddConstraint(
            model_name='identifier',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'substance', 'id_type'), name='uq_identifier_substance_type'),
        ),
    ]
