# Generated by Django 5.2.6 on 2026-04-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('global_sds', '0005_add_property_models_and_substance_fields'),
        ('substances', '0001_initial'),
        ('tenancy', '0002_uc004_hazardous_substance_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=500)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 der hochgeladenen Datei (Duplikaterkennung)', max_length=64)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='Spalten-Zuordnung {excel_col: model_field}')),
                ('status', models.CharField(choices=[('pending', 'Warte auf Bestätigung'), ('processing', 'Wird verarbeitet'), ('done', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Import-Statistik {created: N, updated: N, skipped: N, errors: N}')),
                ('error_message', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Import-Batch',
                'verbose_name_plural': 'Import-Batches',
                'db_table': 'substances_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('trade_name', models.CharField(help_text='Handelsname / Produktbezeichnung', max_length=300)),
                ('material_number', models.CharField(blank=True, default='', help_text='Interne Materialnummer', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('archived', 'Archiviert')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Beschreibung / allgemeiner Verwendungszweck')),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'party_type': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='substances.party')),
                ('sds_revision', models.ForeignKey(blank=True, help_text='Verknüpftes globales SDS (automatisch via CAS-Match)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='global_sds.globalsdsrevision')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'party_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='substances.party')),
            ],
            options={
                'verbose_name': 'Handelsprodukt',
                'verbose_name_plural': 'Handelsprodukte',
                'db_table': 'substances_product',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('row_number', models.PositiveIntegerField(help_text='Zeilennummer in der Excel-Datei')),
                ('raw_data', models.JSONField(default=dict, help_text='Original-Zeile als JSON {spalte: wert}')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warnung'), ('error', 'Fehler'), ('skipped', 'Übersprungen')], default='ok', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list, help_text='Validierungs-/Matching-Hinweise')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='substances.importbatch')),
                ('resolved_product', models.ForeignKey(blank=True, help_text='Zugeordnetes Produkt nach Import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='substances.product')),
            ],
            options={
                'verbose_name': 'Import-Zeile',
                'verbose_name_plural': 'Import-Zeilen',
                'db_table': 'substances_import_row',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Exakte Konzentration in % (bei Reinstoff: 100)', max_digits=7, null=True)),
                ('concentration_min', models.DecimalField(blank=True, decimal_places=4, help_text='Untere Konzentrationsgrenze in %', max_digits=7, null=True)),
                ('concentration_max', models.DecimalField(blank=True, decimal_places=4, help_text='Obere Konzentrationsgrenze in %', max_digits=7, null=True)),
                ('reach_number', models.CharField(blank=True, default='', help_text='REACH-Registrierungsnummer', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='substances.product')),
                ('substance', models.ForeignKey(help_text='Globale Substanz (CAS-basiert)', on_delete=django.db.models.deletion.PROTECT, related_name='product_components', to='global_sds.globalsubstance')),
            ],
            options={
                'verbose_name': 'Produktkomponente',
                'verbose_name_plural': 'Produktkomponenten',
                'db_table': 'substances_product_component',
            },
        ),
        migrations.CreateModel(
            name='RPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_code', models.CharField(help_text='R-Satz Code (z.B. R11, R36/37/38)', max_length=20, unique=True)),
                ('r_text_de', models.TextField(help_text='Deutscher R-Satz Text')),
                ('mapping_notes', models.TextField(blank=True, default='', help_text="Hinweise zur Zuordnung (z.B. 'keine exakte Entsprechung')")),
                ('mapped_h_codes', models.ManyToManyField(blank=True, help_text='Zugeordnete H-Sätze (kann 0..N sein)', related_name='r_phrase_sources', to='substances.hazardstatementref')),
            ],
            options={
                'verbose_name': 'R-Satz (Legacy)',
                'verbose_name_plural': 'R-Sätze (Legacy)',
                'db_table': 'substances_r_phrase',
                'ordering': ['r_code'],
            },
        ),
        migrations.CreateModel(
            name='SPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(help_text='S-Satz Code (z.B. S2, S26, S36/37/39)', max_length=20, unique=True)),
                ('s_text_de', models.TextField(help_text='Deutscher S-Satz Text')),
                ('mapping_notes', models.TextField(blank=True, default='', help_text='Hinweise zur Zuordnung')),
                ('mapped_p_codes', models.ManyToManyField(blank=True, help_text='Zugeordnete P-Sätze (kann 0..N sein)', related_name='s_phrase_sources', to='substances.precautionarystatementref')),
            ],
            options={
                'verbose_name': 'S-Satz (Legacy)',
                'verbose_name_plural': 'S-Sätze (Legacy)',
                'db_table': 'substances_s_phrase',
                'ordering': ['s_code'],
            },
        ),
        migrations.CreateModel(
            name='SubstanceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('usage_description', models.TextField(blank=True, default='', help_text='Verwendungszweck im Betrieb')),
                ('storage_location', models.CharField(blank=True, default='', help_text='Lagerort (z.B. Gefahrstofflager Halle 3)', max_length=300)),
                ('storage_class', models.CharField(blank=True, choices=[('1', '1 - Explosive Stoffe'), ('2A', '2A - Verdichtete Gase'), ('2B', '2B - Druckgaspackungen'), ('3', '3 - Entzündbare Flüssigkeiten'), ('4.1A', '4.1A - Selbstzersetzliche Stoffe'), ('4.1B', '4.1B - Desensibilisierte explosive Stoffe'), ('4.2', '4.2 - Pyrophore/selbsterhitzungsfähige Stoffe'), ('4.3', '4.3 - Stoffe, die mit Wasser reagieren'), ('5.1A', '5.1A - Stark oxidierende Stoffe'), ('5.1B', '5.1B - Oxidierende Stoffe'), ('5.1C', '5.1C - Ammoniumnitrat'), ('5.2', '5.2 - Organische Peroxide'), ('6.1A', '6.1A - Brennbare akut toxische Stoffe'), ('6.1B', '6.1B - Nicht brennbare akut toxische Stoffe'), ('6.1C', '6.1C - Brennbare chronisch toxische Stoffe'), ('6.1D', '6.1D - Nicht brennbare chronisch toxische'), ('6.2', '6.2 - Ansteckungsgefährliche Stoffe'), ('7', '7 - Radioaktive Stoffe'), ('8A', '8A - Brennbare ätzende Stoffe'), ('8B', '8B - Nicht brennbare ätzende Stoffe'), ('10', '10 - Brennbare Flüssigkeiten (nicht LGK 3)'), ('11', '11 - Brennbare Feststoffe'), ('12', '12 - Nicht brennbare Flüssigkeiten'), ('13', '13 - Nicht brennbare Feststoffe')], default='', help_text='Lagerklasse nach TRGS 510 (standortabhängig)', max_length=10)),
                ('aggregate_state', models.CharField(blank=True, choices=[('solid', 'Fest'), ('liquid', 'Flüssig'), ('gas', 'Gasförmig'), ('aerosol', 'Aerosol'), ('paste', 'Pastös')], default='', max_length=20)),
                ('max_storage_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Max. zulässige Lagermenge', max_digits=12, null=True)),
                ('max_storage_unit', models.CharField(choices=[('kg', 'Kilogramm'), ('l', 'Liter'), ('m3', 'Kubikmeter'), ('t', 'Tonnen'), ('pcs', 'Stück')], default='kg', max_length=10)),
                ('annual_consumption', models.DecimalField(blank=True, decimal_places=3, help_text='Jahresverbrauch', max_digits=12, null=True)),
                ('annual_consumption_unit', models.CharField(choices=[('kg', 'Kilogramm'), ('l', 'Liter'), ('m3', 'Kubikmeter'), ('t', 'Tonnen'), ('pcs', 'Stück')], default='kg', max_length=10)),
                ('substitution_status', models.CharField(choices=[('open', 'Offen'), ('done', 'Durchgeführt'), ('not_required', 'Nicht erforderlich')], default='open', max_length=20)),
                ('substitution_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('phased_out', 'Auslaufend')], default='active', max_length=20)),
                ('last_reviewed', models.DateField(blank=True, help_text='Datum der letzten Überprüfung', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substance_usages', to='tenancy.department')),
                ('operating_instruction', models.ForeignKey(blank=True, help_text='Betriebsanweisung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substance_usages_oi', to='documents.documentversion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='substances.product')),
                ('risk_assessment', models.ForeignKey(blank=True, help_text='Gefährdungsbeurteilung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substance_usages_ra', to='documents.documentversion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_usages', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Gefahrstoff-Verwendung',
                'verbose_name_plural': 'Gefahrstoff-Verwendungen',
                'db_table': 'substances_usage',
                'ordering': ['product__trade_name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_product_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'trade_name', 'manufacturer'), name='uq_product_tenant_name_mfr'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uq_import_row_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('product', 'substance'), name='uq_product_component_substance'),
        ),
        migrations.AddIndex(
            model_name='substanceusage',
            index=models.Index(fields=['tenant_id', 'site'], name='ix_usage_tenant_site'),
        ),
        migrations.AddIndex(
            model_name='substanceusage',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_usage_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='substanceusage',
            index=models.Index(fields=['tenant_id', 'substitution_status'], name='ix_usage_tenant_subst_status'),
        ),
        migrations.AddConstraint(
            model_name='substanceusage',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'product', 'site', 'department'), name='uq_usage_product_site_dept'),
        ),
    ]
