# Generated by Django 5.2.6 on 2026-04-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('substances', '0002_uc004_hazardous_substance_register'),
        ('tenancy', '0002_uc004_hazardous_substance_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('reviewer_id', models.UUIDField(db_index=True, help_text='User-ID des Prüfers')),
                ('review_date', models.DateField(help_text='Datum der Prüfung')),
                ('result', models.CharField(choices=[('current', 'Aktuell — keine Änderung'), ('update_required', 'Aktualisierung erforderlich'), ('phased_out', 'Auslaufend / Ersetzt')], max_length=20)),
                ('next_review_date', models.DateField(help_text='Nächste Prüfung fällig am')),
                ('comment', models.TextField(blank=True, default='')),
                ('substance_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reviews', to='substances.substanceusage')),
            ],
            options={
                'verbose_name': 'Compliance-Prüfung',
                'verbose_name_plural': 'Compliance-Prüfungen',
                'db_table': 'substances_compliance_review',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['tenant_id', 'next_review_date'], name='ix_compliance_review_next'), models.Index(fields=['tenant_id', 'result'], name='ix_compliance_review_result')],
                'constraints': [models.UniqueConstraint(fields=('substance_usage', 'review_date'), name='uq_compliance_review_per_date')],
            },
        ),
        migrations.CreateModel(
            name='KatasterRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField(help_text='Fortlaufende Revisionsnummer pro Standort')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Zur Freigabe'), ('approved', 'Freigegeben'), ('superseded', 'Abgelöst')], default='draft', max_length=20)),
                ('snapshot', models.JSONField(default=list, help_text='Kataster-Snapshot: [{product_id, trade_name, manufacturer, ...}]')),
                ('changelog', models.JSONField(default=dict, help_text='Diff zur Vorgänger-Revision: {"added": [], "changed": [], "removed": []}')),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(blank=True, help_text='PDF-Export (Dokumentenlenkung)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kataster_revisions', to='documents.document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kataster_revisions', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Kataster-Revision',
                'verbose_name_plural': 'Kataster-Revisionen',
                'db_table': 'substances_kataster_revision',
                'ordering': ['-revision_number'],
                'indexes': [models.Index(fields=['tenant_id', 'site', 'status'], name='ix_kataster_revision_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'site', 'revision_number'), name='uq_kataster_revision_per_site')],
            },
        ),
        migrations.CreateModel(
            name='SdsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('impact', models.CharField(choices=[('no_impact', 'Keine Auswirkung'), ('informational', 'Informativ'), ('action_required', 'Handlungsbedarf')], default='informational', max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Strukturiertes Diff: {"h_statements": {"added": [...], "removed": [...]}, ...}')),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('new_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs_new', to='substances.sdsrevision')),
                ('old_revision', models.ForeignKey(blank=True, help_text='Vorherige SDS-Revision (NULL bei Ersterfassung)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs_old', to='substances.sdsrevision')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds_change_logs', to='substances.product')),
            ],
            options={
                'verbose_name': 'SDS-Änderungsprotokoll',
                'verbose_name_plural': 'SDS-Änderungsprotokolle',
                'db_table': 'substances_sds_change_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'impact'], name='ix_sds_change_log_impact')],
                'constraints': [models.UniqueConstraint(fields=('product', 'old_revision', 'new_revision'), name='uq_sds_change_log_revisions')],
            },
        ),
    ]
