# Generated by Django 5.2.13 on 2026-04-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0003_compliancereview_katasterrevision_sdschangelog'),
        ('tenancy', '0003_facility_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='katasterrevision',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Produktionsstätte / Werk (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kataster_revisions', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='siteinventoryitem',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Produktionsstätte / Werk (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substance_inventory', to='tenancy.facility'),
        ),
        migrations.AddField(
            model_name='substanceusage',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Produktionsstätte / Werk (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substance_usages', to='tenancy.facility'),
        ),
    ]
