# Generated by Django 5.2.11 on 2026-02-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explosionsschutz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='explosionconcept',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_concepts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='explosionsschutz.equipment'),
        ),
        migrations.AddField(
            model_name='protectionmeasure',
            name='catalog_reference',
            field=models.ForeignKey(blank=True, help_text='Vorlage aus Maßnahmenkatalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='explosionsschutz.measurecatalog'),
        ),
        migrations.AddField(
            model_name='protectionmeasure',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='explosionsschutz.explosionconcept'),
        ),
        migrations.AddField(
            model_name='protectionmeasure',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_measures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protectionmeasure',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referencestandard',
            index=models.Index(fields=['tenant_id', 'category'], name='idx_refstd_tenant_category'),
        ),
        migrations.AddConstraint(
            model_name='referencestandard',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_reference_standard_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='referencestandard',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', True)), fields=('code',), name='uq_reference_standard_global_code'),
        ),
        migrations.AddField(
            model_name='measurecatalog',
            name='reference_standards',
            field=models.ManyToManyField(blank=True, related_name='measure_catalog_entries', to='explosionsschutz.referencestandard'),
        ),
        migrations.AddField(
            model_name='safetyfunction',
            name='reference_standards',
            field=models.ManyToManyField(blank=True, related_name='safety_functions', to='explosionsschutz.referencestandard'),
        ),
        migrations.AddField(
            model_name='protectionmeasure',
            name='safety_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='explosionsschutz.safetyfunction'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='explosionsschutz.explosionconcept'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonedefinition',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='explosionsschutz.explosionconcept'),
        ),
        migrations.AddField(
            model_name='zonedefinition',
            name='reference_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_definitions', to='explosionsschutz.referencestandard'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='explosionsschutz.zonedefinition'),
        ),
        migrations.AddField(
            model_name='zoneignitionsourceassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zoneignitionsourceassessment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignition_assessments', to='explosionsschutz.zonedefinition'),
        ),
        migrations.AddIndex(
            model_name='explosionconcept',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_concept_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='measurecatalog',
            index=models.Index(fields=['tenant_id', 'default_type'], name='idx_meascat_tenant_type'),
        ),
        migrations.AddConstraint(
            model_name='measurecatalog',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'title'), name='uq_measure_catalog_tenant_title'),
        ),
        migrations.AddConstraint(
            model_name='safetyfunction',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uq_safety_function_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['tenant_id', 'next_inspection_date'], name='idx_equip_tenant_inspect'),
        ),
        migrations.AddConstraint(
            model_name='zoneignitionsourceassessment',
            constraint=models.UniqueConstraint(fields=('zone', 'ignition_source'), name='uq_zone_ignition_source'),
        ),
    ]
