# Generated by Django 5.2.6 on 2026-04-22 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0003_add_generation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexIChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(help_text="Nummerierung nach GefStoffV Anhang I, z.B. '1.2(3)'", max_length=20, unique=True)),
                ('requirement_text', models.TextField(help_text='Vollständiger Anforderungstext')),
                ('category', models.CharField(help_text='Fachliche Kategorie für Filterung, z.B. zone_marking, equipment_selection, documentation, inspection', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivierte Einträge werden in neuen Konzepten nicht mehr vorgeschlagen')),
            ],
            options={
                'verbose_name': 'Anhang-I-Checklistenpunkt',
                'verbose_name_plural': 'Anhang-I-Checklistenpunkte',
                'db_table': 'ex_annex_i_checklist_item',
                'ordering': ['clause_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='explosionconcept',
            options={'ordering': ['-created_at'], 'permissions': [('use_ai', 'KI-Augmentierung nutzen (ADR-018)')], 'verbose_name': 'Explosionsschutzkonzept', 'verbose_name_plural': 'Explosionsschutzkonzepte'},
        ),
        migrations.CreateModel(
            name='TrgsK725Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_level', models.CharField(choices=[('a', 'PL a'), ('b', 'PL b'), ('c', 'PL c'), ('d', 'PL d'), ('e', 'PL e')], max_length=1)),
                ('technical_k_level', models.PositiveSmallIntegerField(help_text='K-Klassifizierungsstufe 1 (hoch) bis 3 (niedrig) nach TRGS 725 Tabelle 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('applicable_from', models.DateField(help_text='Gültig ab diesem TRGS-Ausgabedatum')),
                ('applicable_until', models.DateField(blank=True, help_text='Gültig bis (NULL = aktuell gültig)', null=True)),
                ('trgs_version_note', models.CharField(blank=True, help_text="z.B. 'TRGS 725, Ausgabe März 2024'", max_length=100)),
            ],
            options={
                'verbose_name': 'TRGS 725 PL→K Mapping',
                'verbose_name_plural': 'TRGS 725 PL→K Mappings',
                'db_table': 'ex_trgs_k725_mapping',
                'ordering': ['-applicable_from', 'performance_level'],
                'constraints': [models.UniqueConstraint(fields=('performance_level', 'applicable_from'), name='uq_trgs_k725_pl_version')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceStandardClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_path', models.JSONField(help_text="Hierarchische Absatz-Nummerierung, z.B. [2, 3, 1, 2, 'b3']")),
                ('clause_label', models.CharField(help_text="Lesbare Darstellung, z.B. '2.3.1.2 b3)'", max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content_excerpt', models.TextField(blank=True, help_text='Auszug aus dem Regelwerkstext (nicht vollständig, nur für Kontext)')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='explosionsschutz.referencestandard')),
            ],
            options={
                'verbose_name': 'Regelwerks-Klausel',
                'verbose_name_plural': 'Regelwerks-Klauseln',
                'db_table': 'ex_reference_standard_clause',
                'ordering': ['standard', 'clause_label'],
                'indexes': [models.Index(fields=['standard', 'clause_label'], name='idx_ref_clause_std_label')],
            },
        ),
    ]
