# Generated by Django 5.2.6 on 2026-04-22 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0004_phase1a_seed_models'),
        ('substances', '0003_compliancereview_katasterrevision_sdschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedefinition',
            name='atmosphere_form',
            field=models.CharField(blank=True, choices=[('WOLKE', 'Staubwolke (aufgewirbelt)'), ('SCHICHT', 'Staubschicht (abgelagert)'), ('HYBRID', 'Beides relevant (Wolke und Schicht)')], default='', help_text='Nur bei Staubzonen 20/21/22 relevant', max_length=10),
        ),
        migrations.AddField(
            model_name='zonedefinition',
            name='derived_from_clause',
            field=models.ForeignKey(blank=True, help_text='Normative Beispiel-Begründung aus DGUV 113-001 o.ä.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_zones', to='explosionsschutz.referencestandardclause'),
        ),
        migrations.AddField(
            model_name='zonedefinition',
            name='geometry',
            field=models.JSONField(blank=True, help_text="Strukturierte Geometrie statt Freitext, z.B. {'type': 'sphere', 'radius_m': 1.0, 'reference_object': 'Behälterwandung'}", null=True),
        ),
        migrations.AddField(
            model_name='zonedefinition',
            name='zone_condition_type',
            field=models.CharField(choices=[('PERMANENT', 'Dauerhaft vorhanden'), ('MEAS', 'Abhängig von Messung (Gaswarnanlage etc.)'), ('ACTIVITY', 'Tätigkeitsgebunden (Abfüllen, Reinigung etc.)')], default='PERMANENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ConditionalZoneTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('measurement', 'Messtechnisch (Gaswarnanlage, Sensor)'), ('activity', 'Tätigkeitsgebunden (Handlungsanweisung)'), ('time', 'Zeitgebunden (Schichtplan)')], max_length=20)),
                ('measured_variable', models.CharField(blank=True, help_text="z.B. 'H2-Konzentration', 'LEL-Wert am Sensor S-04'", max_length=100)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, help_text='Schwellwert bei dem die Zone aktiv wird', max_digits=10, null=True)),
                ('threshold_unit', models.CharField(blank=True, help_text="z.B. '% UEG', 'mg/m³', 'Vol.%'", max_length=20)),
                ('fallback_zone', models.CharField(blank=True, help_text="Zone-Klassifikation wenn Trigger nicht aktiv (z.B. 'non_ex', '2')", max_length=10)),
                ('activity_name', models.CharField(blank=True, help_text='Bezeichnung der auslösenden Tätigkeit', max_length=200)),
                ('activity_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Typische Dauer der Tätigkeit in Minuten', null=True)),
                ('post_activity_clearance_minutes', models.PositiveIntegerField(blank=True, help_text='Abklingzeit nach Tätigkeitsende bevor Zone wieder als inaktiv gilt', null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Kopie von zone.tenant_id für direkte RLS-Kompatibilität')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='explosionsschutz.zonedefinition')),
            ],
            options={
                'verbose_name': 'Zonen-Auslöser',
                'verbose_name_plural': 'Zonen-Auslöser',
                'db_table': 'ex_conditional_zone_trigger',
            },
        ),
        migrations.CreateModel(
            name='DustSubstanceProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glow_temperature_c', models.DecimalField(blank=True, decimal_places=1, help_text='Glimmtemperatur Staubschicht 5 mm in °C (DIN EN 50281-2-1)', max_digits=6, null=True)),
                ('kst_bar_m_per_s', models.DecimalField(blank=True, decimal_places=1, help_text='KSt-Wert: Höchstwert des norm. Druckanstiegs in bar·m/s (ASTM E1226)', max_digits=6, null=True)),
                ('dust_class', models.CharField(blank=True, choices=[('St0', 'St 0 (inert, nicht explosionsfähig)'), ('St1', 'St 1 (schwach explosiv, KSt ≤ 200 bar·m/s)'), ('St2', 'St 2 (mittel explosiv, KSt 200–300 bar·m/s)'), ('St3', 'St 3 (stark explosiv, KSt > 300 bar·m/s)')], help_text='Staubexplosionsklasse abgeleitet aus KSt (VDI 3673)', max_length=3)),
                ('p_max_bar', models.DecimalField(blank=True, decimal_places=1, help_text='Maximaler Explosionsdruck in bar (ASTM E1226)', max_digits=5, null=True)),
                ('burn_number', models.PositiveSmallIntegerField(blank=True, help_text='Brennzahl BZ 1–6 nach VDI 2263 (1=kaum brennbar, 6=leicht entzündlich)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('particle_size_median_um', models.PositiveIntegerField(blank=True, help_text='Korngröße Median d50 in μm (Siebanalyse). Ex-relevant typisch < 400 μm', null=True)),
                ('moisture_influence_text', models.TextField(blank=True, help_text='Einfluss der Feuchte auf Zündempfindlichkeit und Explosionsfähigkeit')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Kopie von substance.tenant_id für direkte RLS-Kompatibilität')),
                ('substance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dust_properties', to='substances.substance')),
            ],
            options={
                'verbose_name': 'Staub-Kenngrößen',
                'verbose_name_plural': 'Staub-Kenngrößen',
                'db_table': 'ex_dust_substance_properties',
            },
        ),
    ]
