# Generated by Django 5.2.6 on 2026-04-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0005_phase1bc_dust_zone_extensions'),
        ('global_sds', '0005_add_property_models_and_substance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneignitionsourceassessment',
            name='assessment_status',
            field=models.CharField(blank=True, choices=[('NOT_PRESENT', 'Nicht vorhanden'), ('EXCLUDED', 'Vorhanden, aber technisch ausgeschlossen'), ('MITIGATED', 'Vorhanden und wirksam begegnet'), ('ACCEPTED', 'Vorhanden, akzeptiert mit konstruktivem Schutz')], default='', help_text='Vier-wertige Bewertung nach ADR-044. Ersetzt is_present + is_effective nach Datenmigration.', max_length=20),
        ),
        migrations.AlterField(
            model_name='zoneignitionsourceassessment',
            name='is_effective',
            field=models.BooleanField(default=False, help_text='[DEPRECATED ADR-044] Kann diese Zündquelle wirksam werden (Energie ausreichend)?'),
        ),
        migrations.AlterField(
            model_name='zoneignitionsourceassessment',
            name='is_present',
            field=models.BooleanField(default=False, help_text='[DEPRECATED ADR-044] Ist diese Zündquelle im Bereich vorhanden?'),
        ),
        migrations.CreateModel(
            name='AnlageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('ofen', 'Ofen / Reaktor'), ('filter', 'Filter / Entstauber'), ('behaelter', 'Behälter / Tank'), ('foerder', 'Förderanlage'), ('abfuell', 'Abfüll- / Dosieranlage'), ('schrank', 'Gefahrstoffschrank'), ('leitung', 'Rohrleitung / Kanal'), ('pumpe', 'Pumpe / Verdichter'), ('ruehrer', 'Rührer / Mischer'), ('andere', 'Sonstiges')], default='andere', max_length=20)),
                ('commissioning_date', models.DateField(blank=True, help_text='Erstes Inbetriebnahmedatum (relevant für Bestandsschutz)', null=True)),
                ('legacy_installation', models.BooleanField(default=False, help_text='Bestandsanlage ohne ATEX-Zulassung nach § 15 BetrSichV. Entbindet von Vor-Inbetriebnahme-Prüfung, Anhang-I-Punkte 1.8(2-3) entfallen.')),
                ('mobility_type', models.CharField(choices=[('STATIONARY', 'Stationär'), ('MOBILE', 'Mobil'), ('TRANSPORTABLE', 'Transportabel')], default='STATIONARY', max_length=15)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='explosionsschutz.explosionconcept')),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='explosionsschutz.anlagecomponent')),
            ],
            options={
                'verbose_name': 'Anlagenkomponente',
                'verbose_name_plural': 'Anlagenkomponenten',
                'db_table': 'ex_anlage_component',
            },
        ),
        migrations.CreateModel(
            name='ConceptSubstanceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Maßgeblicher Stoff für die Beurteilung'), ('SECONDARY', 'Weiterer Stoff'), ('COMPARISON', 'Vergleichsstoff')], max_length=15)),
                ('release_rate_text', models.TextField(blank=True, help_text='Freitext-Angabe zur Freisetzungsrate für diese Substanz in diesem Konzept')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_references', to='explosionsschutz.explosionconcept')),
                ('sds_revision', models.ForeignKey(help_text='Exakte SDS-Revision zum Erstellungszeitpunkt (Snapshot-Binding, ADR-012)', on_delete=django.db.models.deletion.PROTECT, to='global_sds.globalsdsrevision')),
            ],
            options={
                'verbose_name': 'Konzept-Stoff-Referenz',
                'verbose_name_plural': 'Konzept-Stoff-Referenzen',
                'db_table': 'ex_concept_substance_reference',
            },
        ),
        migrations.CreateModel(
            name='OperationalStateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NORMAL', 'Normalbetrieb'), ('START_STOP', 'An-/Abfahrvorgänge'), ('MALFUNC', 'Fehlbedienung / Störung'), ('ENERGY', 'Energieausfall'), ('MAINT', 'Wartung / Instandhaltung')], max_length=12)),
                ('failure_possible', models.BooleanField(help_text='Ist in diesem Betriebszustand ein Versagen/Fehler möglich?')),
                ('mitigation_measure_text', models.TextField(blank=True, help_text='Gegenmaßnahmen falls failure_possible=True')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_state_assessments', to='explosionsschutz.anlagecomponent')),
            ],
            options={
                'verbose_name': 'Betriebszustands-Bewertung',
                'verbose_name_plural': 'Betriebszustands-Bewertungen',
                'db_table': 'ex_operational_state_assessment',
            },
        ),
        migrations.CreateModel(
            name='SubstanceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('DRUM', 'Fass'), ('CAN', 'Kanister'), ('IBC', 'Intermediate Bulk Container'), ('PRESS', 'Druckgasflasche'), ('TANK', 'Ortsfester Tank'), ('SPRAY', 'Spraydose'), ('CART', 'Kartusche')], max_length=10)),
                ('volume_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Nennvolumen in Litern', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Anzahl Gebinde dieses Typs')),
                ('h_category', models.CharField(blank=True, help_text='Maßgebliche H-Kategorie für TRGS 510, z.B. H224, H225, H226', max_length=5)),
                ('total_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Gesamtmasse (Füllgewicht) in kg (quantity × Einzelmasse)', max_digits=10, null=True)),
                ('protective_cap_valve', models.BooleanField(default=False, help_text='Druckgas: Schutzkappe / Ventilschutz vorhanden (DIN EN ISO 11117)')),
                ('passive_storage', models.BooleanField(default=True, help_text='Passive Lagerung ohne Entnahme im laufenden Betrieb')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='explosionsschutz.explosionconcept')),
                ('substance_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='explosionsschutz.conceptsubstancereference')),
            ],
            options={
                'verbose_name': 'Stoff-Gebinde',
                'verbose_name_plural': 'Stoff-Gebinde',
                'db_table': 'ex_substance_container',
            },
        ),
        migrations.AddConstraint(
            model_name='conceptsubstancereference',
            constraint=models.UniqueConstraint(fields=('concept', 'sds_revision', 'role'), name='uniq_sds_role_per_concept'),
        ),
        migrations.AddConstraint(
            model_name='operationalstateassessment',
            constraint=models.UniqueConstraint(fields=('component', 'state'), name='uniq_state_assessment_per_component'),
        ),
    ]
