# Generated by Django 5.2.6 on 2026-04-22 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('explosionsschutz', '0006_phase2a2b3b_ignition_substances_anlage'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_template_id', models.CharField(help_text='Key des verwendeten Statement-Templates', max_length=50)),
                ('rendered_text', models.TextField(help_text='Fertig gerenderter Freigabe-Text nach Variablen-Ersetzung')),
                ('legal_framework_reference', models.CharField(help_text="z.B. '§ 6(9) GefStoffV i.V.m. § 6(4) BetrSichV'", max_length=100)),
                ('signatory_role', models.CharField(choices=[('ARBEITGEBER', 'Arbeitgeber'), ('BETREIBER', 'Betreiber'), ('AG_BETREIBER', 'Arbeitgeber / Betreiber')], max_length=20)),
                ('signed_by_id', models.UUIDField(help_text='User-UUID des Unterzeichners (kein FK — Audit-Trail bleibt nach User-Löschung erhalten)')),
                ('signed_by_name', models.CharField(max_length=200)),
                ('signed_by_role', models.CharField(help_text='Funktionsbezeichnung des Unterzeichners', max_length=100)),
                ('signed_at', models.DateTimeField()),
                ('digital_signature_hash', models.CharField(blank=True, help_text='SHA-256 Hash der digitalen Signatur (optional)', max_length=128)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_statement', to='explosionsschutz.explosionconcept')),
            ],
            options={
                'verbose_name': 'Freigabe-Erklärung',
                'verbose_name_plural': 'Freigabe-Erklärungen',
                'db_table': 'ex_approval_statement',
            },
        ),
        migrations.CreateModel(
            name='CybersecurityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_framework', models.CharField(blank=True, choices=[('IEC_62443', 'IEC 62443 (Industrial Automation and Control Systems)'), ('NIS2', 'NIS2-Richtlinie (EU 2022/2555)'), ('MVO_2027', 'EU-Maschinenverordnung 2023/1230 (ab Jan 2027)'), ('CUSTOM', 'Anlagen-spezifisch')], max_length=30)),
                ('ot_zone_classification', models.CharField(blank=True, help_text="OT-Sicherheitszone nach IEC 62443, z.B. 'Zone 3 (Control Network)'", max_length=30)),
                ('it_network_isolated', models.BooleanField(default=True, help_text='OT-Netzwerk ist physisch oder logisch vom IT-Netzwerk getrennt')),
                ('access_control_type', models.CharField(choices=[('STAND_ALONE', 'Stand-Alone (keine Netzwerkanbindung)'), ('INTEGRATED', 'In IT-Infrastruktur integriert'), ('REMOTE', 'Fernzugriff möglich')], default='STAND_ALONE', max_length=30)),
                ('hmi_authentication_required', models.BooleanField(default=False, help_text='HMI/Bedienpanel erfordert Authentifizierung')),
                ('security_levels_differentiated', models.BooleanField(default=False, help_text='Unterschiedliche Security Levels (SL) nach IEC 62443 definiert')),
                ('last_security_audit_date', models.DateField(blank=True, null=True)),
                ('threat_analysis_narrative', models.TextField(help_text='Bedrohungsanalyse: identifizierte Angriffsvektoren und Risiken')),
                ('mitigation_measures_narrative', models.TextField(help_text='Gegenmaßnahmen: technische und organisatorische Sicherheitsmaßnahmen')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cybersecurity_assessment', to='explosionsschutz.explosionconcept')),
            ],
            options={
                'verbose_name': 'Cybersecurity-Assessment',
                'verbose_name_plural': 'Cybersecurity-Assessments',
                'db_table': 'ex_cybersecurity_assessment',
            },
        ),
        migrations.CreateModel(
            name='MsrSafetyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('realization_type', models.CharField(choices=[('TECH', 'Technische MSR-Einrichtung (PL nach EN ISO 13849-1)'), ('ORG', 'Organisatorisches Verfahren'), ('COMB', 'Kombiniert technisch und organisatorisch')], max_length=10)),
                ('performance_level', models.CharField(blank=True, choices=[('a', 'PL a'), ('b', 'PL b'), ('c', 'PL c'), ('d', 'PL d'), ('e', 'PL e')], help_text='Required Performance Level nach EN ISO 13849-1 (nur bei TECH/COMB)', max_length=1)),
                ('verification_report_ref', models.CharField(blank=True, help_text="z.B. 'Marquis-AF-23-0135-001-1' (Prüfberichtnummer)", max_length=200)),
                ('verification_method', models.CharField(blank=True, choices=[('SISTEMA', 'SISTEMA (BGIA Tool)'), ('MANUAL', 'Manuelle FMEA'), ('EXTERNAL', 'Externer Prüfbericht (zPbP / ZÜS)')], max_length=20)),
                ('technical_k_level', models.PositiveSmallIntegerField(blank=True, help_text='K=1/2/3 rein technisch aus PL abgeleitet (via TrgsK725Mapping)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('organizational_contribution_text', models.TextField(blank=True, help_text='Beschreibung des organisatorischen Anteils bei realization_type=ORG/COMB')),
                ('resulting_k_level', models.PositiveSmallIntegerField(blank=True, help_text='K=1/2/3 final (technisch + organisatorisch kombiniert, TRGS 725 Tabelle 3)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('evaluation_narrative', models.TextField(help_text='Freitext-Begründung der MSR-Bewertung (Pflichtfeld)')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_functions', to='explosionsschutz.explosionconcept')),
                ('target_zone', models.ForeignKey(blank=True, help_text='Angestrebte Zoneneinteilung nach MSR-Maßnahme', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msr_functions_target_zone', to='explosionsschutz.zonedefinition')),
                ('zone_without_msr', models.ForeignKey(blank=True, help_text='Zoneneinteilung vor der MSR-Maßnahme', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msr_functions_initial_zone', to='explosionsschutz.zonedefinition')),
            ],
            options={
                'verbose_name': 'MSR-Sicherheitsfunktion',
                'verbose_name_plural': 'MSR-Sicherheitsfunktionen',
                'db_table': 'ex_msr_safety_function',
            },
        ),
        migrations.CreateModel(
            name='ReviewScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulatory_layer', models.CharField(choices=[('TRGS_722', 'Primärer Schutz (TRGS 722)'), ('TRGS_723', 'Sekundärer Schutz (TRGS 723)'), ('TRGS_724', 'Konstruktiver Schutz (TRGS 724)'), ('TRGS_725', 'MSR-Schutz (TRGS 725)'), ('FIRE', 'Brandschutz'), ('EFFECT', 'Wirksamkeitsprüfung (§ 6(9) GefStoffV)')], max_length=15)),
                ('measure_description', models.CharField(help_text='Bezeichnung der Prüfmaßnahme', max_length=200)),
                ('legal_basis', models.CharField(help_text="z.B. 'TRGS 722 i.V.m. § 7(7) GefStoffV'", max_length=100)),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Prüfintervall in Monaten (NULL = einmalig oder ereignisgetriggert)', null=True)),
                ('first_due_date', models.DateField(blank=True, help_text='Erste Fälligkeit (Inbetriebnahme oder Erstellungsdatum)', null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='Wird automatisch aus last_completed_date + interval_months berechnet', null=True)),
                ('inspector_role', models.CharField(choices=[('zPbP', 'Zur Prüfung befähigte Person (zPbP)'), ('ZUeS', 'Zugelassene Überwachungsstelle (ZÜS)'), ('AG', 'Arbeitgeber'), ('FF', 'Fachfirma')], help_text='Wer muss diese Prüfung durchführen?', max_length=10)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule_entries', to='explosionsschutz.explosionconcept')),
            ],
            options={
                'verbose_name': 'Prüfplan-Eintrag',
                'verbose_name_plural': 'Prüfplan-Einträge',
                'db_table': 'ex_review_schedule_entry',
                'ordering': ['concept', 'regulatory_layer', 'next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnexIChecklistAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_APPLICABLE', 'Nicht erforderlich'), ('COMPLIANT', 'Erfüllt'), ('NON_COMPLIANT', 'Nicht erfüllt'), ('PENDING', 'In Bearbeitung')], default='PENDING', max_length=20)),
                ('evidence_text', models.TextField(blank=True, help_text='Nachweis-Text oder Verweis auf Dokumentation')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annex_i_assessments', to='explosionsschutz.explosionconcept')),
                ('corrective_action_link', models.ForeignKey(blank=True, help_text='Verknüpfte offene Maßnahme bei NON_COMPLIANT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annex_i_assessments', to='actions.actionitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='explosionsschutz.annexichecklistitem')),
            ],
            options={
                'verbose_name': 'Anhang-I-Bewertung',
                'verbose_name_plural': 'Anhang-I-Bewertungen',
                'db_table': 'ex_annex_i_checklist_assessment',
                'constraints': [models.UniqueConstraint(fields=('concept', 'item'), name='uniq_annex_i_per_concept')],
            },
        ),
        migrations.CreateModel(
            name='ConceptApprovalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_version', models.PositiveIntegerField()),
                ('zones_snapshot_json', models.JSONField(help_text='Serialisierte ZoneDefinitions zum Freigabe-Zeitpunkt')),
                ('ignition_sources_snapshot_json', models.JSONField(help_text='Serialisierte ZoneIgnitionSourceAssessments zum Freigabe-Zeitpunkt')),
                ('safety_functions_snapshot_json', models.JSONField(help_text='Serialisierte MsrSafetyFunctions zum Freigabe-Zeitpunkt')),
                ('review_schedule_snapshot_json', models.JSONField(help_text='Serialisierte ReviewScheduleEntries zum Freigabe-Zeitpunkt')),
                ('annex_i_assessment_snapshot_json', models.JSONField(help_text='Serialisierte AnnexIChecklistAssessments zum Freigabe-Zeitpunkt')),
                ('substance_references_snapshot_json', models.JSONField(help_text='Serialisierte ConceptSubstanceReferences zum Freigabe-Zeitpunkt')),
                ('operational_states_snapshot_json', models.JSONField(default=list, help_text='OperationalStateAssessments zum Freigabe-Zeitpunkt eingefroren')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='explosionsschutz.approvalstatement')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_snapshots', to='explosionsschutz.explosionconcept')),
            ],
            options={
                'verbose_name': 'Freigabe-Snapshot',
                'verbose_name_plural': 'Freigabe-Snapshots',
                'db_table': 'ex_concept_approval_snapshot',
                'default_permissions': ('add', 'view'),
                'constraints': [models.UniqueConstraint(fields=('concept', 'snapshot_version'), name='uniq_snapshot_per_version')],
            },
        ),
        migrations.CreateModel(
            name='ConceptDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_note', models.CharField(blank=True, help_text="z.B. 'Primäres SDB für Zonenbewertung' oder 'Verfahrensplan Raum 04.01'", max_length=200)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='explosionsschutz.explosionconcept')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concept_links', to='projects.projectdocument')),
            ],
            options={
                'verbose_name': 'Konzept-Dokument-Link',
                'verbose_name_plural': 'Konzept-Dokument-Links',
                'db_table': 'concept_document_link',
                'constraints': [models.UniqueConstraint(fields=('concept', 'document'), name='uniq_document_per_concept')],
            },
        ),
    ]
