# Generated by Django 5.2.6 on 2026-04-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0007_phase3a4a4b5a_msr_cyber_review_approval'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosionconcept',
            name='project',
            field=models.ForeignKey(blank=True, help_text='ADR-041 Container. Nach Phase 3 der Datenmigration: null=False.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='explosion_concepts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='explosionconcept',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='Fachliche Revisionsnummer (getrennt von der internen Versions-ID)'),
        ),
        migrations.AddField(
            model_name='explosionconcept',
            name='storage_mode',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Aktive Lagerung'), ('PASSIVE', 'Passive Lagerung'), ('PROCESS', 'Verfahrensanlage')], default='', help_text='Lagerungs- / Prozess-Charakter der Anlage', max_length=10),
        ),
        migrations.AlterField(
            model_name='explosionconcept',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_PROGRESS', 'In Bearbeitung'), ('REVIEW', 'In Prüfung'), ('APPROVED', 'Freigegeben'), ('APPROVED_WITH_ACTIONS', 'Freigegeben mit offenen Maßnahmen'), ('REVIEW_REQUIRED', 'Überprüfung erforderlich'), ('ARCHIVED', 'Archiviert')], default='DRAFT', max_length=30),
        ),
    ]
