# Generated by Django 5.2.6 on 2026-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0008_phase7_project_fk_status_extensions'),
        ('global_sds', '0005_add_property_models_and_substance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptsubstancereference',
            name='sds_revision',
            field=models.ForeignKey(blank=True, help_text='Exakte SDS-Revision zum Erstellungszeitpunkt (Snapshot-Binding, ADR-012). Darf NULL sein während der Datenmigration (substance_id → ConceptSubstanceReference). Nach Phase 4 Deprecation: null=False erzwingen.', null=True, on_delete=django.db.models.deletion.PROTECT, to='global_sds.globalsdsrevision'),
        ),
    ]
