# Generated by Django 5.2.6 on 2026-04-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0011_data_project_assignment_and_harden'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosionconcept',
            name='project',
            field=models.ForeignKey(help_text='ADR-041 Container (ADR-044 Phase 3). Pflichtfeld nach Datenmigration 0011.', on_delete=django.db.models.deletion.PROTECT, related_name='explosion_concepts', to='projects.project'),
        ),
    ]
