# Generated by Django 5.2.13 on 2026-04-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explosionsschutz', '0012_phase3_project_fk_helptext'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explosionconcept',
            name='project',
            field=models.ForeignKey(blank=True, help_text='ADR-041 Container (ADR-044 Phase 3). Optional beim Erstellen, Zuweisung im Workflow.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='explosion_concepts', to='projects.project'),
        ),
    ]
