# Generated by Django 5.2.6 on 2026-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('inspection_due', 'Prüfung fällig'), ('inspection_overdue', 'Prüfung überfällig'), ('measure_due', 'Maßnahme fällig'), ('measure_overdue', 'Maßnahme überfällig'), ('concept_status', 'Konzept-Status'), ('sds_expiring', 'SDB läuft ab'), ('sds_review_due', 'SDS-Prüfung fällig'), ('training_due', 'Unterweisung fällig'), ('training_overdue', 'Unterweisung überfällig'), ('substitution_due', 'Substitutionsprüfung fällig'), ('gefbu_review_due', 'GefBu-Prüfung fällig'), ('approval_required', 'Freigabe erforderlich'), ('system', 'System')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('inspection_due', 'Prüfung fällig'), ('inspection_overdue', 'Prüfung überfällig'), ('measure_due', 'Maßnahme fällig'), ('measure_overdue', 'Maßnahme überfällig'), ('concept_status', 'Konzept-Status'), ('sds_expiring', 'SDB läuft ab'), ('sds_review_due', 'SDS-Prüfung fällig'), ('training_due', 'Unterweisung fällig'), ('training_overdue', 'Unterweisung überfällig'), ('substitution_due', 'Substitutionsprüfung fällig'), ('gefbu_review_due', 'GefBu-Prüfung fällig'), ('approval_required', 'Freigabe erforderlich'), ('system', 'System')], max_length=30),
        ),
    ]
