# Generated by Django 5.2.13 on 2026-04-29 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_facility_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file', models.FileField(upload_to='intake/%Y/%m/', verbose_name='Datei')),
                ('doc_type', models.CharField(blank=True, max_length=100, verbose_name='Erkannter Typ')),
                ('doc_type_confidence', models.CharField(blank=True, max_length=10, verbose_name='Konfidenz')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Extrahierter Text')),
                ('suggested_targets', models.JSONField(default=list, verbose_name='Vorgeschlagene Ziele')),
                ('selected_targets', models.JSONField(default=list, verbose_name='Ausgewählte Ziele')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'Wird verarbeitet'), ('done', 'Fertig'), ('error', 'Fehler')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_uploads', to='tenancy.facility', verbose_name='Betrieb')),
            ],
            options={
                'verbose_name': 'Intake Upload',
                'verbose_name_plural': 'Intake Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_code', models.CharField(max_length=50, verbose_name='Ziel')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Fehler'), ('skipped', 'Übersprungen')], max_length=10, verbose_name='Status')),
                ('result_id', models.IntegerField(blank=True, null=True, verbose_name='Ergebnis-ID')),
                ('result_url', models.CharField(blank=True, max_length=500, verbose_name='Ergebnis-URL')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='intake.intakeupload', verbose_name='Upload')),
            ],
            options={
                'verbose_name': 'Intake Result',
                'verbose_name_plural': 'Intake Results',
                'unique_together': {('upload', 'target_code')},
            },
        ),
    ]
