# Generated by Django 5.2.13 on 2026-04-14 12:47

import django.db.models.deletion
import gbu.models.activity
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Denormalisiert von HazardAssessmentActivity.tenant_id (ADR-003)')),
                ('tops_type', models.CharField(choices=[('S', 'Substitution'), ('T', 'Technical'), ('O', 'Organisational'), ('P', 'Personal')], max_length=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('legal_basis', models.CharField(blank=True, default='', max_length=200)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Vom Nutzer bestätigt (nicht nur Vorlage)')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GBU-Schutzmaßnahme',
                'verbose_name_plural': 'GBU-Schutzmaßnahmen',
                'db_table': 'gbu_activity_measure',
                'ordering': ['tops_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung der Tätigkeitsvorlage', max_length=200)),
                ('scope', models.CharField(choices=[('system', 'Systemvorlage (global)'), ('tenant', 'Mandanten-Vorlage')], db_index=True, default='system', max_length=10)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Nur bei scope=tenant gesetzt; NULL = systemweite Vorlage', null=True)),
                ('activity_description', models.TextField(help_text='Vorausgefüllte Tätigkeitsbeschreibung')),
                ('activity_frequency', models.CharField(blank=True, choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('occasional', 'Gelegentlich'), ('rare', 'Selten')], default='', max_length=15)),
                ('quantity_class', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L')], default='', max_length=2)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Typische Expositionsdauer in Minuten', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tätigkeitsvorlage',
                'verbose_name_plural': 'Tätigkeitsvorlagen',
                'db_table': 'gbu_activity_template',
                'ordering': ['scope', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HazardCategoryRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category_type', models.CharField(choices=[('fire_explosion', 'fire_explosion'), ('acute_toxic', 'acute_toxic'), ('chronic_toxic', 'chronic_toxic'), ('skin_corrosion', 'skin_corrosion'), ('eye_damage', 'eye_damage'), ('respiratory', 'respiratory'), ('skin_sens', 'skin_sens'), ('cmr', 'cmr'), ('environment', 'environment'), ('asphyxiant', 'asphyxiant')], db_index=True, max_length=30)),
                ('trgs_reference', models.CharField(blank=True, default='', help_text="z.B. 'TRGS 400 Abschnitt 5.3'", max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gefährdungskategorie',
                'verbose_name_plural': 'Gefährdungskategorien',
                'db_table': 'gbu_hazard_category_ref',
                'ordering': ['category_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HCodeCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.CharField(db_index=True, help_text="z.B. 'H220', 'H301'", max_length=10)),
                ('annotation', models.TextField(blank=True, default='', help_text='Begründung / TRGS-Verweis')),
            ],
            options={
                'verbose_name': 'H-Code Mapping',
                'verbose_name_plural': 'H-Code Mappings',
                'db_table': 'gbu_h_code_category_mapping',
                'ordering': ['h_code'],
            },
        ),
        migrations.CreateModel(
            name='MeasureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops_type', models.CharField(choices=[('S', 'Substitution'), ('T', 'Technical'), ('O', 'Organisational'), ('P', 'Personal')], db_index=True, max_length=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('legal_basis', models.CharField(blank=True, default='', help_text="z.B. 'GefStoffV §7, TRGS 500'", max_length=200)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Pflichtmaßnahme (keine Ablehnung möglich)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Maßnahmen-Vorlage',
                'verbose_name_plural': 'Maßnahmen-Vorlagen',
                'db_table': 'gbu_measure_template',
                'ordering': ['tops_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExposureRiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_class', models.CharField(choices=[('xs', 'XS (<1L/kg)'), ('s', 'S (1–10L/kg)'), ('m', 'M (10–100L/kg)'), ('l', 'L (>100L/kg)')], help_text='Mengenkategorie nach EMKG', max_length=2)),
                ('activity_frequency', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('occasional', 'Gelegentlich'), ('rare', 'Selten')], help_text='Expositionsfrequenz', max_length=15)),
                ('has_cmr', models.BooleanField(default=False, help_text='Enthält CMR-Stoff (Karzinogen/Mutagen/Reproduktionstoxisch)')),
                ('risk_score', models.CharField(choices=[('low', 'Gering (EMKG A)'), ('medium', 'Mittel (EMKG B)'), ('high', 'Hoch (EMKG C)'), ('critical', 'Kritisch')], help_text='Resultierender Risikoscore nach EMKG', max_length=10)),
                ('emkg_class', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', help_text='EMKG-Expositionsklasse (A/B/C)', max_length=1)),
                ('note', models.TextField(blank=True, default='', help_text='Begründung / Rechtsgrundlage (TRGS 400, EMKG-Leitfaden)')),
            ],
            options={
                'verbose_name': 'EMKG-Risikomatrix-Eintrag',
                'verbose_name_plural': 'EMKG-Risikomatrix',
                'db_table': 'gbu_exposure_risk_matrix',
                'ordering': ['quantity_class', 'activity_frequency'],
                'unique_together': {('quantity_class', 'activity_frequency', 'has_cmr')},
            },
        ),
        migrations.CreateModel(
            name='HazardAssessmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('activity_description', models.TextField(help_text='Tätigkeitsbeschreibung (was wird gemacht, womit, wie lange)')),
                ('activity_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('occasional', 'Occasional'), ('rare', 'Rare')], max_length=15)),
                ('duration_minutes', models.PositiveSmallIntegerField(help_text='Expositionsdauer in Minuten pro Vorgang')),
                ('quantity_class', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L')], help_text='Mengenkategorie nach EMKG', max_length=2)),
                ('substitution_checked', models.BooleanField(default=False, help_text='Substitutionsprüfung nach §7 GefStoffV durchgeführt')),
                ('substitution_notes', models.TextField(blank=True, default='')),
                ('risk_score', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', help_text='EMKG-Risikostufe (berechnet)', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('outdated', 'Outdated')], db_index=True, default=gbu.models.activity.ActivityStatus['DRAFT'], max_length=10)),
                ('approved_by_id', models.UUIDField(blank=True, db_index=True, help_text='UUID der freigebenden Person (unveränderlich nach Freigabe)', null=True)),
                ('approved_by_name', models.CharField(blank=True, default='', help_text='Vollname der freigebenden Person (Snapshot, immutable nach Freigabe)', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='Nächste Überprüfung (GefStoffV §6)', null=True)),
                ('ba_document', models.ForeignKey(blank=True, help_text='Generierte Betriebsanweisung (TRGS 555)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion')),
                ('gbu_document', models.ForeignKey(blank=True, help_text='Generiertes GBU-PDF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'GBU-Tätigkeit',
                'verbose_name_plural': 'GBU-Tätigkeiten',
                'db_table': 'gbu_hazard_assessment_activity',
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
    ]
