# Generated by Django 5.2.13 on 2026-04-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gbu', '0001_initial'),
        ('substances', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardassessmentactivity',
            name='sds_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gbu_activities', to='substances.sdsrevision'),
        ),
        migrations.AddField(
            model_name='hazardassessmentactivity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gbu_activities', to='tenancy.site'),
        ),
        migrations.AddField(
            model_name='activitymeasure',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='gbu.hazardassessmentactivity'),
        ),
        migrations.AddField(
            model_name='hazardassessmentactivity',
            name='derived_hazard_categories',
            field=models.ManyToManyField(blank=True, help_text='Auto-abgeleitete Gefährdungskategorien (via H-Code-Mapping)', related_name='activities', to='gbu.hazardcategoryref'),
        ),
        migrations.AddField(
            model_name='activitytemplate',
            name='default_hazard_categories',
            field=models.ManyToManyField(blank=True, help_text='Voreingestellte Gefährdungskategorien', related_name='activity_templates', to='gbu.hazardcategoryref'),
        ),
        migrations.AddField(
            model_name='hcodecategorymapping',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_code_mappings', to='gbu.hazardcategoryref'),
        ),
        migrations.AddField(
            model_name='measuretemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_templates', to='gbu.hazardcategoryref'),
        ),
        migrations.AddField(
            model_name='activitymeasure',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Vorlage aus der Datenbank (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='gbu.measuretemplate'),
        ),
        migrations.AddIndex(
            model_name='hazardassessmentactivity',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_gbu_activity_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='hazardassessmentactivity',
            index=models.Index(fields=['tenant_id', 'next_review_date'], name='ix_gbu_activity_review_date'),
        ),
        migrations.AddConstraint(
            model_name='activitytemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'tenant')), fields=('tenant_id', 'name'), name='uq_gbu_activity_template_tenant_name'),
        ),
        migrations.AlterUniqueTogether(
            name='hcodecategorymapping',
            unique_together={('h_code', 'category')},
        ),
    ]
