# Generated by Django 5.2.6 on 2026-04-22 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explosionsschutz', '0007_phase3a4a4b5a_msr_cyber_review_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSchutzGutachten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('compliance_anchor', models.ForeignKey(blank=True, help_text='Optional: UC-1-Konzept als Datenquelle für KI-Prefill. Ermöglicht fieldprefill.prefill_field() mit strukturierten Konzept-Daten.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gutachten', to='explosionsschutz.explosionconcept')),
            ],
            options={
                'verbose_name': 'Ex-Schutz-Gutachten',
                'verbose_name_plural': 'Ex-Schutz-Gutachten',
                'db_table': 'ex_schutz_gutachten',
            },
        ),
    ]
