# Generated by Django 5.2.6 on 2026-04-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exschutzdokument', '0001_initial_ex_schutz_gutachten'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exschutzgutachten',
            name='project',
            field=models.ForeignKey(blank=True, help_text='ADR-041 Container. UC-2 ist direkt im Projekt verankert.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex_schutz_gutachten', to='projects.project'),
        ),
    ]
