# Generated by Django 5.2.10 on 2026-01-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionitem',
            new_name='actions_act_tenant__b3fc2f_idx',
            old_name='actions_act_tenant__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='actionitem',
            new_name='actions_act_tenant__5fe16c_idx',
            old_name='actions_act_tenant__d4e5f6_idx',
        ),
    ]
