# Generated by Django 5.2.13 on 2026-04-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brandschutz', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireprotectionconcept',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fire_protection_concepts', to='tenancy.site'),
        ),
        migrations.AddField(
            model_name='filledtemplate',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_templates', to='brandschutz.fireprotectionconcept'),
        ),
        migrations.AddField(
            model_name='conceptdocument',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_documents', to='brandschutz.fireprotectionconcept'),
        ),
        migrations.AddField(
            model_name='fireprotectionmeasure',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='brandschutz.fireprotectionconcept'),
        ),
        migrations.AddField(
            model_name='firesection',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='brandschutz.fireprotectionconcept'),
        ),
        migrations.AddField(
            model_name='fireprotectionmeasure',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional: Zugeordneter Brandabschnitt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='brandschutz.firesection'),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_extinguishers', to='brandschutz.firesection'),
        ),
        migrations.AddField(
            model_name='escaperoute',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_routes', to='brandschutz.firesection'),
        ),
        migrations.AddIndex(
            model_name='concepttemplatestore',
            index=models.Index(fields=['tenant_id', 'scope'], name='ix_bs_ctmpl_tenant_scope'),
        ),
        migrations.AddIndex(
            model_name='fireprotectionconcept',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_concept_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='fireprotectionconcept',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'outdated'])), name='ck_brandschutz_concept_status'),
        ),
        migrations.AddIndex(
            model_name='filledtemplate',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_ftmpl_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='conceptdocument',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_cdoc_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='firesection',
            constraint=models.UniqueConstraint(fields=('concept', 'name'), name='uq_bs_section_name_concept'),
        ),
        migrations.AddIndex(
            model_name='fireprotectionmeasure',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_measure_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='fireextinguisher',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_ext_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='fireextinguisher',
            index=models.Index(fields=['tenant_id', 'next_inspection_date'], name='ix_bs_ext_inspection'),
        ),
    ]
