# Generated by Django 5.2.12 on 2026-03-26 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandschutz', '0002_conceptdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptTemplateStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(default='brandschutz', max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_master', models.BooleanField(default=False)),
                ('framework', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(choices=[('analyzed', 'Aus Dokumentanalyse'), ('builtin', 'Framework-Vorlage'), ('merged', 'Zusammengeführt'), ('manual', 'Manuell erstellt')], default='analyzed', max_length=20)),
                ('template_json', models.TextField(help_text='Serialisiertes ConceptTemplate (Pydantic JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konzept-Template',
                'verbose_name_plural': 'Konzept-Templates',
                'db_table': 'brandschutz_concept_template_store',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FilledTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=240)),
                ('values_json', models.TextField(default='{}', help_text='JSON: {section_name: {field_name: value}}')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben'), ('exported', 'Exportiert')], db_index=True, default='draft', max_length=20)),
                ('generated_pdf_key', models.CharField(blank=True, default='', help_text='S3-Pfad des generierten PDFs', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ausgefülltes Template',
                'verbose_name_plural': 'Ausgefüllte Templates',
                'db_table': 'brandschutz_filled_template',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='firesection',
            name='uq_brandschutz_section_name_per_concept',
        ),
        migrations.RenameIndex(
            model_name='fireextinguisher',
            new_name='ix_bs_ext_tenant_status',
            old_name='ix_brandschutz_ext_tenant_status',
        ),
        migrations.RenameIndex(
            model_name='fireextinguisher',
            new_name='ix_bs_ext_inspection',
            old_name='ix_brandschutz_ext_inspection',
        ),
        migrations.RenameIndex(
            model_name='fireprotectionconcept',
            new_name='ix_bs_concept_tenant_status',
            old_name='ix_brandschutz_concept_tenant_status',
        ),
        migrations.RenameIndex(
            model_name='fireprotectionmeasure',
            new_name='ix_bs_measure_tenant_status',
            old_name='ix_brandschutz_measure_tenant_status',
        ),
        migrations.AlterField(
            model_name='escaperoute',
            name='description',
            field=models.TextField(help_text="Wegbeschreibung (z.B. 'Treppenhaus Nord → Ausgang Hof')"),
        ),
        migrations.AlterField(
            model_name='escaperoute',
            name='door_width_m',
            field=models.FloatField(blank=True, help_text='Türbreite in Metern', null=True),
        ),
        migrations.AlterField(
            model_name='escaperoute',
            name='is_signposted',
            field=models.BooleanField(default=False, help_text='Rettungszeichenleuchten vorhanden'),
        ),
        migrations.AlterField(
            model_name='escaperoute',
            name='length_m',
            field=models.FloatField(blank=True, help_text='Länge des Fluchtwegs in Metern', null=True),
        ),
        migrations.AlterField(
            model_name='escaperoute',
            name='width_m',
            field=models.FloatField(blank=True, help_text='Lichte Breite in Metern (Mindestanforderung: 0,9 m)', null=True),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='capacity_kg',
            field=models.FloatField(help_text='Füllmenge in kg (z.B. 6 kg für ABC-Löscher)'),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='fire_class',
            field=models.CharField(blank=True, default='', help_text="Brandklassen (z.B. 'A, B, C' oder 'F')", max_length=20),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='location_description',
            field=models.CharField(help_text="Standortbeschreibung (z.B. 'Wand neben Notausgang Ost')", max_length=300),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='next_inspection_date',
            field=models.DateField(blank=True, help_text='Nächste Prüfung (BGV A3 / DGUV V3, alle 2 Jahre)', null=True),
        ),
        migrations.AlterField(
            model_name='fireprotectionconcept',
            name='responsible_user_id',
            field=models.UUIDField(blank=True, help_text='Verantwortlicher Brandschutzbeauftragter', null=True),
        ),
        migrations.AlterField(
            model_name='fireprotectionconcept',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Nächste Überprüfung / Ablaufdatum', null=True),
        ),
        migrations.AlterField(
            model_name='fireprotectionmeasure',
            name='legal_basis',
            field=models.CharField(blank=True, default='', help_text="z.B. 'MBO §14', 'ASR A2.3', 'DGUV R 215-220'", max_length=200),
        ),
        migrations.AlterField(
            model_name='fireprotectionmeasure',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Optional: Zugeordneter Brandabschnitt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='brandschutz.firesection'),
        ),
        migrations.AlterField(
            model_name='firesection',
            name='area_sqm',
            field=models.FloatField(blank=True, help_text='Fläche in m²', null=True),
        ),
        migrations.AlterField(
            model_name='firesection',
            name='fire_load_mj_m2',
            field=models.FloatField(blank=True, help_text='Brandlast in MJ/m² (nach DIN 18230)', null=True),
        ),
        migrations.AlterField(
            model_name='firesection',
            name='floor',
            field=models.CharField(blank=True, default='', help_text="Stockwerk/Etage (z.B. 'EG', '1.OG', 'UG')", max_length=50),
        ),
        migrations.AlterField(
            model_name='firesection',
            name='max_occupancy',
            field=models.PositiveIntegerField(blank=True, help_text='Maximale Personenanzahl (für Fluchtwegberechnung)', null=True),
        ),
        migrations.AddConstraint(
            model_name='firesection',
            constraint=models.UniqueConstraint(fields=('concept', 'name'), name='uq_bs_section_name_concept'),
        ),
        migrations.AddField(
            model_name='concepttemplatestore',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_templates', to='brandschutz.conceptdocument'),
        ),
        migrations.AddField(
            model_name='filledtemplate',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_templates', to='brandschutz.fireprotectionconcept'),
        ),
        migrations.AddField(
            model_name='filledtemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filled_instances', to='brandschutz.concepttemplatestore'),
        ),
        migrations.AddIndex(
            model_name='concepttemplatestore',
            index=models.Index(fields=['tenant_id', 'scope'], name='ix_bs_ctmpl_tenant_scope'),
        ),
        migrations.AddIndex(
            model_name='filledtemplate',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_bs_ftmpl_tenant_status'),
        ),
    ]
