# Generated by Django 5.2.11 on 2026-02-09 15:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'approvals_decision',
                'ordering': ['decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(db_index=True, help_text="z.B. 'explosionsschutz.ExplosionConcept'", max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('in_review', 'In Prüfung'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('withdrawn', 'Zurückgezogen')], db_index=True, default='pending', max_length=15)),
                ('current_step', models.IntegerField(default=1, help_text='Currently active step order number')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approvals_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Reihenfolge der Freigabestufe (1, 2, 3...)')),
                ('name', models.CharField(help_text="z.B. 'Fachliche Prüfung', 'Freigabe GF'", max_length=200)),
                ('required_permission', models.CharField(blank=True, default='', help_text='Permission code required to approve this step', max_length=100)),
                ('require_comment', models.BooleanField(default=False, help_text='Kommentar bei Freigabe erforderlich')),
            ],
            options={
                'db_table': 'approvals_step',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workflow_type', models.CharField(choices=[('ex_concept', 'Ex-Schutz-Konzept'), ('risk_assessment', 'Risikobewertung'), ('protection_measure', 'Schutzmaßnahme')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'approvals_workflow',
            },
        ),
    ]
