# Generated by Django 5.2.6 on 2026-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='workflow_type',
            field=models.CharField(choices=[('ex_concept', 'Ex-Schutz-Konzept'), ('risk_assessment', 'Risikobewertung'), ('protection_measure', 'Schutzmaßnahme'), ('kataster_revision', 'Kataster-Revision'), ('sds_review', 'SDS-Prüfung'), ('gefbu_review', 'GefBu-Prüfung')], db_index=True, max_length=30),
        ),
    ]
