# Generated by Django 5.2.6 on 2026-04-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('substances', '0003_compliancereview_katasterrevision_sdschangelog'),
        ('tenancy', '0002_uc004_hazardous_substance_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('interval', models.CharField(choices=[('annual', 'Jährlich'), ('semi_annual', 'Halbjährlich'), ('quarterly', 'Vierteljährlich'), ('on_change', 'Bei Änderung')], default='annual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_topics', to='tenancy.department')),
                ('products', models.ManyToManyField(blank=True, help_text='Verknüpfte Gefahrstoffe/Produkte', related_name='training_topics', to='substances.product')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_topics', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Unterweisungsthema',
                'verbose_name_plural': 'Unterweisungsthemen',
                'db_table': 'training_topic',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('trainer_id', models.UUIDField(db_index=True, help_text='User-ID des Unterweisenden')),
                ('session_date', models.DateField(help_text='Datum der Unterweisung')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('completed', 'Durchgeführt'), ('cancelled', 'Abgesagt')], default='planned', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, help_text='Unterweisungsnachweis (PDF/Scan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='documents.document')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.trainingtopic')),
            ],
            options={
                'verbose_name': 'Unterweisungs-Veranstaltung',
                'verbose_name_plural': 'Unterweisungs-Veranstaltungen',
                'db_table': 'training_session',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True, help_text='User-ID des Teilnehmers')),
                ('status', models.CharField(choices=[('present', 'Anwesend'), ('absent', 'Abwesend'), ('excused', 'Entschuldigt'), ('makeup', 'Nachschulung')], default='present', max_length=10)),
                ('signed_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der digitalen Unterschrift / Bestätigung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.trainingsession')),
            ],
            options={
                'verbose_name': 'Teilnahme-Nachweis',
                'verbose_name_plural': 'Teilnahme-Nachweise',
                'db_table': 'training_attendance',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='ix_attendance_tenant_user')],
                'constraints': [models.UniqueConstraint(fields=('session', 'user_id'), name='uq_attendance_session_user')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingtopic',
            index=models.Index(fields=['tenant_id', 'is_active'], name='ix_training_topic_active'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant_id', 'session_date'], name='ix_training_session_date'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_training_session_status'),
        ),
    ]
