# Generated by Django 5.2.13 on 2026-04-14 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', help_text='Dokumenttyp, z.B. ex_schutz, gbu, brandschutz', max_length=50)),
                ('structure_json', models.TextField(default='{"sections": []}', help_text='Template-Struktur als JSON')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('accepted', 'Akzeptiert'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dokumentvorlage',
                'verbose_name_plural': 'Dokumentvorlagen',
                'db_table': 'project_doc_template',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='ix_doctmpl_tenant_status')],
            },
        ),
        migrations.CreateModel(
            name='OutputDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(help_text='Dokumenttyp, z.B. ex_schutz, gbu, brandschutz', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Verwendete Dokumentvorlage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_documents', to='projects.documenttemplate')),
            ],
            options={
                'verbose_name': 'Ausgabedokument',
                'verbose_name_plural': 'Ausgabedokumente',
                'db_table': 'project_output_document',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('fields_json', models.TextField(blank=True, default='[]', help_text='Felddefinitionen als JSON (aus Template-Struktur)')),
                ('values_json', models.TextField(blank=True, default='{}', help_text='Feldwerte als JSON {field_key: value}')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.outputdocument')),
            ],
            options={
                'verbose_name': 'Dokumentabschnitt',
                'verbose_name_plural': 'Dokumentabschnitte',
                'db_table': 'project_document_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.CharField(blank=True, default='', max_length=50)),
                ('client_name', models.CharField(blank=True, default='', help_text='Auftraggeber', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Freitext-Beschreibung für KI-Modulempfehlung')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('on_hold', 'Pausiert'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='outputdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_documents', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('sds', 'Sicherheitsdatenblatt'), ('plan', 'Grundriss/Anlagenplan'), ('gutachten', 'Bestehendes Gutachten'), ('regulation', 'Regelwerk/Norm'), ('process', 'Verfahrensbeschreibung'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='projects/docs/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projektunterlage',
                'verbose_name_plural': 'Projektunterlagen',
                'db_table': 'project_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, help_text="Modul-Code z.B. 'explosionsschutz', 'gbu'", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('declined', 'Bewusst abgelehnt'), ('deactivated', 'Nachträglich deaktiviert')], default='active', max_length=20)),
                ('is_ai_recommended', models.BooleanField(default=False)),
                ('ai_reason', models.TextField(blank=True, default='', help_text='KI-Begründung für Empfehlung')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='projects.project')),
            ],
            options={
                'verbose_name': 'Projekt-Modul',
                'verbose_name_plural': 'Projekt-Module',
                'db_table': 'project_module',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_project_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='projectmodule',
            constraint=models.UniqueConstraint(fields=('project', 'module'), name='uq_project_module'),
        ),
    ]
