# Generated by Django 5.2.13 on 2026-04-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdocument',
            name='template',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
    ]
