# Generated by Django 5.2.13 on 2026-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='ai_context_hint',
            field=models.TextField(blank=True, default='', help_text='LLM-generierte Retrieval-Hinweise für diesen Abschnitt (beim Erstellen generiert)'),
        ),
    ]
