# Generated by Django 5.2.13 on 2026-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_section_ai_context_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='ai_prompt',
            field=models.TextField(blank=True, default='', help_text='Editierbarer KI-Prompt für diesen Abschnitt (wird beim KI ausfüllen/verbessern verwendet)'),
        ),
    ]
