# Generated by Django 5.2.11 on 2026-02-18 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0002_add_avv_measure_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('subject_name', models.CharField(max_length=200, verbose_name='Name der betroffenen Person')),
                ('subject_email', models.EmailField(max_length=254, verbose_name='E-Mail der betroffenen Person')),
                ('subject_reference', models.CharField(blank=True, help_text='Interne Referenz zur Identifikation', max_length=100, verbose_name='Referenz / Kundennummer')),
                ('request_date', models.DateField(verbose_name='Antragsdatum')),
                ('request_description', models.TextField(help_text='Welche Daten sollen gelöscht werden?', verbose_name='Beschreibung des Löschantrags')),
                ('data_categories', models.TextField(blank=True, verbose_name='Betroffene Datenkategorien')),
                ('status', models.CharField(choices=[('pending', 'Beantragt'), ('auth_sent', 'Authentifizierung angefordert'), ('auth_received', 'Authentifizierung erhalten'), ('deletion_ordered', 'Löschung beauftragt'), ('deletion_confirmed', 'Löschung bestätigt'), ('notified', 'Betroffener benachrichtigt'), ('closed', 'Abgeschlossen'), ('rejected', 'Abgelehnt')], db_index=True, default='pending', max_length=30)),
                ('auth_sent_at', models.DateTimeField(blank=True, null=True)),
                ('auth_received_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('auth_notes', models.TextField(blank=True, verbose_name='Notizen Authentifizierung')),
                ('deletion_notes', models.TextField(blank=True, verbose_name='Notizen Löschung')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('assigned_to_id', models.UUIDField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests', to='dsb.mandate')),
            ],
            options={
                'verbose_name': 'Löschantrag',
                'verbose_name_plural': 'Löschanträge',
                'db_table': 'dsb_deletion_request',
                'ordering': ['-request_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_dsb_delreq_tenant_status'), models.Index(fields=['tenant_id', 'mandate'], name='idx_dsb_delreq_tenant_mandate')],
            },
        ),
    ]
