# Generated by Django 5.2.11 on 2026-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0003_add_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='breach',
            name='authority_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='authority_name',
            field=models.CharField(blank=True, help_text='z.B. LfDI Baden-Württemberg', max_length=200, verbose_name='Aufsichtsbehörde'),
        ),
        migrations.AddField(
            model_name='breach',
            name='authority_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='authority_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='authority_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aktenzeichen Behörde'),
        ),
        migrations.AddField(
            model_name='breach',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='dsb_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='dsb_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='remediation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='remediation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='reported_by_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Meldender'),
        ),
        migrations.AddField(
            model_name='breach',
            name='reported_by_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gemeldet von'),
        ),
        migrations.AddField(
            model_name='breach',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='breach',
            name='updated_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breach',
            name='workflow_status',
            field=models.CharField(choices=[('reported', 'Panne gemeldet'), ('dsb_notified', 'DSB kontaktiert'), ('authority_notified', 'Behörde benachrichtigt'), ('remediation', 'Behebung läuft'), ('resolved', 'Panne behoben'), ('authority_closed', 'Behörde informiert (Abschluss)'), ('closed', 'Abgeschlossen')], db_index=True, default='reported', max_length=30),
        ),
    ]
