# Generated by Django 5.2.11 on 2026-02-18 17:59

import django.db.models.deletion
import dsb.models.document
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsb', '0004_add_breach_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsbDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('ref_type', models.CharField(choices=[('avv', 'AVV (Art. 28)'), ('vvt', 'VVT (Art. 30)'), ('tom', 'TOM (Art. 32)'), ('breach', 'Datenpanne (Art. 33)'), ('deletion', 'Löschantrag (Art. 17)'), ('mandate', 'Mandat'), ('general', 'Allgemein')], db_index=True, default='general', max_length=20)),
                ('ref_id', models.UUIDField(blank=True, db_index=True, help_text='UUID des verknüpften Objekts (AVV, Breach, DeletionRequest, etc.)', null=True)),
                ('file', models.FileField(upload_to=dsb.models.document._upload_path, verbose_name='Datei')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(help_text='Kurzbeschreibung des Dokuments', max_length=300, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('document_date', models.DateField(blank=True, help_text='Datum des Dokuments (z.B. Unterzeichnungsdatum)', null=True, verbose_name='Dokumentdatum')),
                ('uploaded_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='dsb.mandate')),
            ],
            options={
                'verbose_name': 'DSB-Dokument',
                'verbose_name_plural': 'DSB-Dokumente',
                'db_table': 'dsb_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'ref_type', 'ref_id'], name='idx_dsb_doc_tenant_ref'), models.Index(fields=['tenant_id', 'mandate'], name='idx_dsb_doc_tenant_mandate')],
            },
        ),
    ]
