# Generated by Django 5.2.13 on 2026-04-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=240)),
                ('category', models.CharField(choices=[('brandschutz', 'Brandschutz'), ('explosionsschutz', 'Explosionsschutz'), ('arbeitssicherheit', 'Arbeitssicherheit'), ('nachweis', 'Nachweis'), ('general', 'Allgemein'), ('sdb', 'Sicherheitsdatenblatt'), ('gefaehrdungsbeurteilung', 'Gefährdungsbeurteilung'), ('betriebsanweisung', 'Betriebsanweisung'), ('unterweisung', 'Unterweisungsnachweis'), ('pruefbericht', 'Prüfbericht')], default='general', max_length=50)),
                ('concept_ref_id', models.UUIDField(blank=True, db_index=True, help_text='Optional: Verknüpfung zu Brandschutz-/Explosionsschutzkonzept', null=True)),
                ('scope', models.CharField(blank=True, default='', help_text='Fachbereich: brandschutz, explosionsschutz, etc.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_document',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'title'), name='uq_doc_title_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('s3_key', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'db_table': 'documents_document_version',
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='uq_doc_version')],
            },
        ),
    ]
