# Generated by Django 5.2.11 on 2026-02-09 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_tenancy', '0002_module_subscription_module_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions_role',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('manage', 'Manage'), ('export', 'Export'), ('approve', 'Approve')], default='view', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions_permission',
                'indexes': [models.Index(fields=['module', 'resource'], name='idx_perm_module_resource')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.role')),
            ],
            options={
                'db_table': 'permissions_role_permission',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='permissions.RolePermission', to='permissions.permission'),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('scope_type', models.CharField(choices=[('TENANT', 'Tenant'), ('SITE', 'Site'), ('ASSET', 'Asset')], max_length=12)),
                ('site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('asset_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions_scope',
                'constraints': [models.CheckConstraint(condition=models.Q(('scope_type__in', ['TENANT', 'SITE', 'ASSET'])), name='ck_scope_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'SITE'), _negated=True), ('site_id__isnull', False), _connector='OR'), name='scope_site_chk'), models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'ASSET'), _negated=True), ('asset_id__isnull', False), _connector='OR'), name='scope_asset_chk')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='permissions.role')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.scope')),
            ],
            options={
                'db_table': 'permissions_assignment',
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(help_text='True = grant, False = deny')),
                ('reason', models.TextField(blank=True, default='')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='django_tenancy.membership')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission')),
            ],
            options={
                'db_table': 'permissions_override',
                'constraints': [models.UniqueConstraint(fields=('membership', 'permission'), name='override_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='uq_permissions_role_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant_id', 'user_id'], name='idx_assignment_user'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'user_id', 'role', 'scope'), name='uq_assignment'),
        ),
    ]
