# Generated by Django 5.2.13 on 2026-04-14 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSdsComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=512)),
                ('cas_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('ec_number', models.CharField(blank=True, default='', max_length=20)),
                ('concentration_min', models.DecimalField(blank=True, decimal_places=4, help_text='Untere Konzentrationsgrenze (%)', max_digits=7, null=True)),
                ('concentration_max', models.DecimalField(blank=True, decimal_places=4, help_text='Obere Konzentrationsgrenze (%)', max_digits=7, null=True)),
                ('concentration_note', models.CharField(blank=True, default='', max_length=100)),
                ('m_factor_acute', models.PositiveSmallIntegerField(blank=True, help_text='M-Faktor (akut)', null=True)),
                ('m_factor_chronic', models.PositiveSmallIntegerField(blank=True, help_text='M-Faktor (chronisch)', null=True)),
            ],
            options={
                'verbose_name': 'SDS-Inhaltsstoff',
                'verbose_name_plural': 'SDS-Inhaltsstoffe',
                'db_table': 'global_sds_sdscomponent',
            },
        ),
        migrations.CreateModel(
            name='GlobalSdsExposureLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('AGW', 'Arbeitsplatzgrenzwert (TRGS 900)'), ('STEL', 'Kurzzeitgrenzwert'), ('TWA', 'Zeitgewichteter Mittelwert'), ('BGW', 'Biologischer Grenzwert (TRGS 903)'), ('DNEL_W', 'DNEL Arbeitnehmer'), ('DNEL_C', 'DNEL Verbraucher'), ('PNEC', 'PNEC Umwelt')], max_length=10)),
                ('route', models.CharField(choices=[('INH', 'Einatmung'), ('DERM', 'Haut'), ('ORAL', 'Oral'), ('FW', 'Süßwasser'), ('MW', 'Meerwasser'), ('SOIL', 'Boden'), ('STP', 'Abwasserkläranlage')], max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=40)),
                ('effect_type', models.CharField(blank=True, default='', max_length=100)),
                ('basis', models.CharField(blank=True, default='', help_text='Rechtsgrundlage (z.B. TRGS 900)', max_length=100)),
            ],
            options={
                'verbose_name': 'Expositionsgrenzwert',
                'verbose_name_plural': 'Expositionsgrenzwerte',
                'db_table': 'global_sds_sdsexposurelimit',
            },
        ),
        migrations.CreateModel(
            name='GlobalSdsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_hash', models.CharField(help_text='SHA-256 des Original-PDFs (Idempotenz)', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend (nur Uploader)'), ('VERIFIED', 'Verifiziert (global)'), ('REJECTED', 'Abgelehnt'), ('SUPERSEDED', 'Abgelöst')], default='PENDING', max_length=20)),
                ('uploaded_by_tenant_id', models.UUIDField(db_index=True, help_text='Tenant der dieses SDS hochgeladen hat')),
                ('manufacturer_name', models.CharField(blank=True, default='', max_length=256)),
                ('product_name', models.CharField(max_length=512)),
                ('revision_date', models.DateField(blank=True, help_text='Revisionsdatum des SDS', null=True)),
                ('version_number', models.CharField(blank=True, default='', max_length=20)),
                ('wgk', models.PositiveSmallIntegerField(blank=True, help_text='Wassergefährdungsklasse (1-3)', null=True)),
                ('storage_class_trgs510', models.CharField(blank=True, default='', help_text='Lagerklasse nach TRGS 510', max_length=5)),
                ('voc_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('voc_g_per_l', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flash_point_c', models.DecimalField(blank=True, decimal_places=2, help_text='Flammpunkt in °C', max_digits=7, null=True)),
                ('ignition_temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='Zündtemperatur in °C', max_digits=7, null=True)),
                ('lower_explosion_limit', models.DecimalField(blank=True, decimal_places=3, help_text='UEG in Vol.%', max_digits=6, null=True)),
                ('upper_explosion_limit', models.DecimalField(blank=True, decimal_places=3, help_text='OEG in Vol.%', max_digits=6, null=True)),
                ('parse_confidence', models.FloatField(blank=True, help_text='Gesamt-Konfidenz des Regex-Parsers (0.0-1.0)', null=True)),
                ('llm_corrections', models.JSONField(blank=True, default=list, help_text='Audit-Trail der LLM-Korrekturen')),
                ('signal_word', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Globale SDS-Revision',
                'verbose_name_plural': 'Globale SDS-Revisionen',
                'db_table': 'global_sds_sdsrevision',
                'ordering': ['-revision_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number (z.B. 111-76-2)', max_length=20, null=True, unique=True)),
                ('ec_number', models.CharField(blank=True, default='', help_text='EC/EINECS-Nummer', max_length=20)),
                ('name', models.CharField(help_text='IUPAC oder gebräuchlicher Name', max_length=512)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='Alternative Namen (z.B. Handelsnamen)')),
                ('chemical_formula', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Globale Substanz',
                'verbose_name_plural': 'Globale Substanzen',
                'db_table': 'global_sds_substance',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SdsRevisionDiffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_impact', models.CharField(choices=[('SAFETY_CRITICAL', 'Safety Critical'), ('REGULATORY', 'Regulatory'), ('INFORMATIONAL', 'Informational')], max_length=20)),
                ('field_diffs', models.JSONField(help_text='Serialisierte FieldDiff-Liste')),
                ('added_h_codes', models.JSONField(default=list)),
                ('removed_h_codes', models.JSONField(default=list)),
                ('changed_components', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SDS-Revisions-Diff',
                'verbose_name_plural': 'SDS-Revisions-Diffs',
                'db_table': 'global_sds_revisiondiff',
            },
        ),
        migrations.CreateModel(
            name='SdsUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant-ID für Mandantentrennung')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('PENDING_APPROVAL', 'Wartet auf Freigabe'), ('REVIEW_REQUIRED', 'Überprüfung erforderlich (Safety Critical)'), ('UPDATE_AVAILABLE', 'Update verfügbar (Regulatory)'), ('SUPERSEDED', 'Abgelöst'), ('WITHDRAWN', 'Zurückgezogen')], default='PENDING_APPROVAL', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, default='')),
                ('pending_update_impact', models.CharField(blank=True, default='', max_length=20)),
                ('review_deadline', models.DateField(blank=True, help_text='Frist für Review (GefStoffV §7)', null=True)),
                ('update_deferred_reason', models.TextField(blank=True, default='', help_text='Pflichtbegründung bei Zurückstellung')),
                ('update_deferred_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SDS-Nutzung (Tenant)',
                'verbose_name_plural': 'SDS-Nutzungen (Tenant)',
                'db_table': 'global_sds_usage',
            },
        ),
    ]
