# Generated by Django 5.2.13 on 2026-04-14 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_sds', '0001_initial'),
        ('substances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsdscomponent',
            name='hazard_statements',
            field=models.ManyToManyField(blank=True, related_name='global_sds_components', to='substances.hazardstatementref'),
        ),
        migrations.AddField(
            model_name='globalsdsexposurelimit',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposure_limits', to='global_sds.globalsdscomponent'),
        ),
        migrations.AddField(
            model_name='globalsdsrevision',
            name='hazard_statements',
            field=models.ManyToManyField(blank=True, related_name='global_sds_revisions', to='substances.hazardstatementref'),
        ),
        migrations.AddField(
            model_name='globalsdsrevision',
            name='pictograms',
            field=models.ManyToManyField(blank=True, related_name='global_sds_revisions', to='substances.pictogramref'),
        ),
        migrations.AddField(
            model_name='globalsdsrevision',
            name='precautionary_statements',
            field=models.ManyToManyField(blank=True, related_name='global_sds_revisions', to='substances.precautionarystatementref'),
        ),
        migrations.AddField(
            model_name='globalsdsrevision',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='globalsdsexposurelimit',
            name='sds_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_limits', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='globalsdscomponent',
            name='sds_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='globalsdsrevision',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='global_sds.globalsubstance'),
        ),
        migrations.AddField(
            model_name='sdsrevisiondiffrecord',
            name='new_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diffs_as_new', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='sdsrevisiondiffrecord',
            name='old_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diffs_as_old', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='sdsusage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sds_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sdsusage',
            name='pending_update_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_for_usages', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='sdsusage',
            name='sds_revision',
            field=models.ForeignKey(help_text='Globale SDS-Revision (BetrSichV Audit-Immutabilität)', on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddField(
            model_name='sdsusage',
            name='update_deferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_sds_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='globalsdsexposurelimit',
            constraint=models.UniqueConstraint(fields=('sds_revision', 'component', 'limit_type', 'route'), name='uq_exposure_limit_per_component_route'),
        ),
        migrations.AddIndex(
            model_name='globalsdsrevision',
            index=models.Index(fields=['source_hash'], name='ix_global_sds_source_hash'),
        ),
        migrations.AddIndex(
            model_name='globalsdsrevision',
            index=models.Index(fields=['status', 'uploaded_by_tenant_id'], name='ix_global_sds_status_tenant'),
        ),
        migrations.AddConstraint(
            model_name='globalsdsrevision',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_by', models.F('id')), _negated=True), name='chk_sdsrevision_no_self_supersession'),
        ),
        migrations.AddConstraint(
            model_name='sdsrevisiondiffrecord',
            constraint=models.UniqueConstraint(fields=('old_revision', 'new_revision'), name='uq_diff_per_revision_pair'),
        ),
        migrations.AddIndex(
            model_name='sdsusage',
            index=models.Index(fields=['tenant_id', 'status'], name='ix_sds_usage_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='sdsusage',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'sds_revision'), name='uq_sds_usage_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sdsusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='chk_sds_usage_active_requires_approver'),
        ),
    ]
