# Generated by Django 5.2.13 on 2026-04-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_sds', '0004_pg_trgm_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdsPropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Interner Schlüssel (z.B. 'flash_point', 'density')", max_length=100, unique=True)),
                ('label_de', models.CharField(help_text='Deutscher Anzeigename', max_length=200)),
                ('label_en', models.CharField(blank=True, default='', max_length=200)),
                ('sds_section', models.CharField(blank=True, default='', help_text="SDS-Abschnitt (z.B. '9.1', '14.1')", max_length=10)),
                ('value_type', models.CharField(choices=[('NUMERIC', 'Numerisch (Einzelwert)'), ('NUMERIC_RANGE', 'Numerisch (Bereich)'), ('NUMERIC_AT_TEMP', 'Numerisch bei Temperatur'), ('BOOLEAN', 'Boolean'), ('ENUM', 'Enum (Auswahlliste)'), ('TEXT', 'Freitext')], default='NUMERIC', max_length=20)),
                ('unit', models.CharField(blank=True, default='', help_text="Standard-Einheit (z.B. '°C', 'mg/m³')", max_length=40)),
                ('extraction_patterns', models.JSONField(blank=True, default=list, help_text='Regex-Patterns für Parser [{pattern, group, transform}]')),
                ('is_promoted', models.BooleanField(default=False, help_text='True wenn als dedizierte Spalte auf SdsRevision existiert')),
                ('promoted_column_name', models.CharField(blank=True, default='', help_text='Spaltenname auf GlobalSdsRevision (wenn promoted)', max_length=100)),
                ('coverage_percent', models.FloatField(default=0.0, help_text='Anteil der Revisionen mit diesem Property (%)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SDS-Eigenschaftsdefinition',
                'verbose_name_plural': 'SDS-Eigenschaftsdefinitionen',
                'db_table': 'global_sds_propertydefinition',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SdsRevisionProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_numeric_lo', models.DecimalField(blank=True, decimal_places=4, help_text='Unterer Wert (oder Einzelwert)', max_digits=12, null=True)),
                ('value_numeric_hi', models.DecimalField(blank=True, decimal_places=4, help_text='Oberer Wert (bei Bereich)', max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, default='', help_text='Textwert (bei ENUM/TEXT/BOOLEAN)', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Original-Text aus dem SDS (für Audit/Suche)')),
                ('confidence', models.FloatField(default=1.0, help_text='Konfidenz des Parsers (0.0-1.0)')),
                ('parse_source', models.CharField(blank=True, default='', help_text='Extraktionsquelle (regex, llm, manual)', max_length=20)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='Bezugstemperatur (bei NUMERIC_AT_TEMP)', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'SDS-Revisions-Eigenschaft',
                'verbose_name_plural': 'SDS-Revisions-Eigenschaften',
                'db_table': 'global_sds_revisionproperty',
            },
        ),
        migrations.AddField(
            model_name='globalsubstance',
            name='cas_number_normalized',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Auto-normalisierte CAS (ohne Trennzeichen) für Lookup', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsubstance',
            name='common_name_de',
            field=models.CharField(blank=True, default='', help_text='Gebräuchlicher deutscher Name', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='globalsubstance',
            constraint=models.UniqueConstraint(condition=models.Q(('cas_number_normalized__gt', '')), fields=('cas_number_normalized',), name='uq_substance_cas_normalized'),
        ),
        migrations.AddField(
            model_name='sdsrevisionproperty',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='global_sds.sdspropertydefinition'),
        ),
        migrations.AddField(
            model_name='sdsrevisionproperty',
            name='sds_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='global_sds.globalsdsrevision'),
        ),
        migrations.AddIndex(
            model_name='sdsrevisionproperty',
            index=models.Index(fields=['definition', 'value_numeric_lo'], name='ix_revprop_def_numeric'),
        ),
        migrations.AddConstraint(
            model_name='sdsrevisionproperty',
            constraint=models.UniqueConstraint(fields=('sds_revision', 'definition'), name='uq_revision_property_per_def'),
        ),
    ]
