# Generated by Django 6.0.4 on 2026-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_sds', '0005_add_property_models_and_substance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsdsrevision',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Original-PDF (BetrSichV Archivierungspflicht)', null=True, upload_to='sds/pdfs/'),
        ),
    ]
