# Generated by Django 6.0.4 on 2026-04-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_sds', '0006_add_pdf_file_to_global_sds_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsdsrevision',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Vollständige extrahierte + angereicherte Daten (parse_result + enrichment)'),
        ),
    ]
