# Generated by Django 5.2.6 on 2026-04-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', help_text="Abteilungskürzel (z.B. 'PROD', 'HT')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_department',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, default='', help_text="Standortkürzel (z.B. 'A', 'FR')", max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('plant', 'Werk'), ('warehouse', 'Lager'), ('office', 'Büro'), ('lab', 'Labor'), ('other', 'Sonstiges')], default='plant', help_text='Standorttyp', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant_id', 'code'), name='uq_site_code_per_tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Standort (leer = standortübergreifend)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenancy.site'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'organization', 'site', 'name'), name='uq_department_per_org_site'),
        ),
    ]
