# Generated by Django 5.2.13 on 2026-04-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_uc004_hazardous_substance_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', help_text="Kürzel (z.B. 'H1', 'R2')", max_length=20)),
                ('facility_type', models.CharField(choices=[('production', 'Produktion'), ('storage', 'Lager'), ('lab', 'Labor'), ('office', 'Büro'), ('workshop', 'Werkstatt'), ('other', 'Sonstiges')], default='production', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='tenancy.site')),
            ],
            options={
                'db_table': 'tenancy_facility',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'site', 'name'), name='uq_facility_name_per_site'), models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant_id', 'site', 'code'), name='uq_facility_code_per_site')],
            },
        ),
    ]
