# Generated by Django 5.2.11 on 2026-02-09 15:27

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('resource_type', models.CharField(db_index=True, help_text="Type of resource (e.g., 'Risk', 'Action', 'Document')", max_length=100)),
                ('resource_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the affected resource', null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional event details as JSON')),
                ('request_id', models.CharField(blank=True, default='', help_text='Request ID for correlation', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client user agent')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='audit_tenant_time_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx')],
            },
        ),
    ]
