# Generated by Django 5.2.13 on 2026-04-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('brandschutz', 'Brandschutz'), ('explosionsschutz', 'Explosionsschutz'), ('arbeitssicherheit', 'Arbeitssicherheit'), ('arbeitsschutz', 'Arbeitsschutz'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_assessment',
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_assessment_tenant_status'), models.Index(fields=['tenant_id', 'category'], name='idx_assessment_tenant_category')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'archived'])), name='ck_assessment_status_valid'), models.UniqueConstraint(fields=('tenant_id', 'title'), name='uq_assessment_title_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.IntegerField(choices=[(1, 'Gering'), (2, 'Mittel'), (3, 'Hoch'), (4, 'Sehr hoch'), (5, 'Kritisch')], default=1)),
                ('probability', models.IntegerField(choices=[(1, 'Unwahrscheinlich'), (2, 'Selten'), (3, 'Gelegentlich'), (4, 'Wahrscheinlich'), (5, 'Häufig')], default=1)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('residual_risk', models.IntegerField(blank=True, null=True)),
                ('mitigation_status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('mitigated', 'Gemindert'), ('accepted', 'Akzeptiert')], db_index=True, default='open', max_length=15)),
                ('responsible_user_id', models.UUIDField(blank=True, db_index=True, help_text='UUID der verantwortlichen Person für die Maßnahme', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Fälligkeitsdatum der Maßnahme', null=True)),
                ('substance_id', models.UUIDField(blank=True, db_index=True, help_text='Verknüpfter Gefahrstoff (substances.Substance, optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='risk.assessment')),
            ],
            options={
                'db_table': 'risk_hazard',
                'indexes': [models.Index(fields=['tenant_id', 'assessment'], name='idx_hazard_tenant_assessment'), models.Index(fields=['tenant_id', 'mitigation_status'], name='idx_hazard_tenant_status'), models.Index(fields=['tenant_id', 'due_date'], name='idx_hazard_tenant_due_date')],
            },
        ),
    ]
