# Generated by Django 5.2.10 on 2026-01-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessment',
            new_name='risk_assess_tenant__0c27a8_idx',
            old_name='risk_assess_tenant__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='assessment',
            new_name='risk_assess_tenant__6b6ac7_idx',
            old_name='risk_assess_tenant__g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='hazard',
            new_name='risk_hazard_tenant__7766e2_idx',
            old_name='risk_hazard_tenant__a1b2c3_idx',
        ),
    ]
