# Generated by Django 5.2.6 on 2026-04-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
        ('substances', '0002_uc004_hazardous_substance_register'),
        ('tenancy', '0002_uc004_hazardous_substance_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='hazard',
            name='substance_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Standort / Bereich', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='tenancy.site'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Verknüpftes Handelsprodukt (UC-004+)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_entries', to='substances.product'),
        ),
        migrations.CreateModel(
            name='ProtectiveMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('measure_type', models.CharField(choices=[('substitution', 'Substitution (S)'), ('technical', 'Technische Maßnahme (T)'), ('organizational', 'Organisatorische Maßnahme (O)'), ('personal', 'Persönliche Schutzausrüstung (P)')], db_index=True, max_length=20)),
                ('description', models.TextField(help_text='Beschreibung der Maßnahme')),
                ('specification', models.TextField(blank=True, default='', help_text="PSA-Details, Produktspezifikation (z.B. 'Nitrilhandschuhe, Durchbruchzeit >480 min')")),
                ('norm_reference', models.CharField(blank=True, default='', help_text="Norm-Referenz (z.B. 'EN 374', 'TRGS 510')", max_length=200)),
                ('responsible_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('implemented', 'Umgesetzt'), ('not_possible', 'Nicht umsetzbar')], db_index=True, default='open', max_length=20)),
                ('effectiveness_checked_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_result', models.CharField(choices=[('effective', 'Wirksam'), ('partially', 'Teilweise wirksam'), ('ineffective', 'Unwirksam'), ('not_checked', 'Nicht geprüft')], default='not_checked', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protective_measures', to='risk.assessment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protective_measures', to='tenancy.department')),
                ('hazard', models.ForeignKey(blank=True, help_text='Verknüpfte Gefährdung (NULL = Assessment-übergreifend)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protective_measures', to='risk.hazard')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protective_measures', to='tenancy.site')),
            ],
            options={
                'verbose_name': 'Schutzmaßnahme',
                'verbose_name_plural': 'Schutzmaßnahmen',
                'db_table': 'risk_protective_measure',
                'ordering': ['measure_type', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_measure_tenant_status'), models.Index(fields=['tenant_id', 'measure_type'], name='idx_measure_tenant_type'), models.Index(fields=['tenant_id', 'due_date'], name='idx_measure_tenant_due')],
            },
        ),
        migrations.CreateModel(
            name='SubstitutionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('result', models.CharField(choices=[('possible', 'Substitution möglich'), ('not_possible', 'Nicht möglich (begründet)'), ('not_required', 'Nicht erforderlich')], max_length=20)),
                ('justification', models.TextField(help_text="Begründung (insbes. bei 'nicht möglich')")),
                ('checked_by', models.UUIDField(db_index=True)),
                ('checked_at', models.DateTimeField()),
                ('implementation_deadline', models.DateField(blank=True, help_text='Umsetzungsfrist bei positivem Ergebnis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_product', models.ForeignKey(blank=True, help_text='Vorgeschlagenes Alternativprodukt (NULL wenn nicht möglich)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_checks_alternative', to='substances.product')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitution_checks', to='risk.assessment')),
                ('current_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_checks_current', to='substances.product')),
                ('substance_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_checks', to='substances.substanceusage')),
            ],
            options={
                'verbose_name': 'Substitutionsprüfung',
                'verbose_name_plural': 'Substitutionsprüfungen',
                'db_table': 'risk_substitution_check',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['tenant_id', 'result'], name='idx_subst_check_result')],
            },
        ),
    ]
