# Generated by Django 5.2.13 on 2026-04-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_remove_assessment_site_id_remove_hazard_substance_id_and_more'),
        ('substances', '0003_compliancereview_katasterrevision_sdschangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitutioncheck',
            name='current_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitution_checks_current', to='substances.product'),
        ),
        migrations.AlterField(
            model_name='substitutioncheck',
            name='substance_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitution_checks', to='substances.substanceusage'),
        ),
    ]
